### ISSUE TITLE
입지, 거리보다 중요한 경로당 구조

### ISSUE THREAD

**Issue by OSSnewb** [pwjdgus/Data_Analytics_for_Age_friendly_busan#101]
경로당의 구조에 따른 남녀 이용비율과 장단점이 잘 나와있는 자료입니다. 
<a> https://www.koreascience.or.kr/article/JAKO201426059104969.pdf

**Comment by pwjdgus** [comment]
자료 내용을 요약해 주시는게 좋아보입니다

**Comment by OSSnewb** [comment]
R: 노인들의 순수 공간 L: 거실이라고 했을때 
1. R형  2. L-R형  3. R-L-R형 4. L-R-R형 5. R-R형 총 5개의 구조로 나뉩니다. 
여성은 친목도모, 여가활등을 주로 즐겨 R을 선호하고 남성은 취미활동, 정보교환, 공동작업장 등 다소 활동적인 것을 즐겨 L을 선호합니다.  
이러한 성별간의 구조 선호도로 인해 거주지 근처에 적절한 구조의 경로당이 없다면 성별간의 경로당 이용 편차가 생길 것입다.
따라서 지역별 노인 성별 비율을 조사하여 적절한 구조의 경로당이 필요하다고 생각합니다. 

![Notes_220412_223806_48a](https://user-images.githubusercontent.com/100742423/162975732-14f2c69b-c8c8-470c-ae25-0ffbbfb19e5c.jpg)

**Comment by BlueArcticFox** [comment]
급속하게 진행되는 고령화사회에 경로당의 수가 부족한 점에서 착안하여, 데이터를 기반으로 한 최적의 경로당 입지를 선정하는 해당 프로젝트에서 경로당의 구조까지 생각하는 것은 현재 단계에서는 다소 벗어나지 않았나 생각됩니다.

허나 경로당의 이해도면에서는 도움이 되었습니다. 좋은자료 감사합니다.

**Comment by OSSnewb** [comment]
아이디어가 좋아서 작성해봤는데 생각해보니 방향성에 맞지 않는 내용이네요. 지적 감사합니다.
