### ISSUE TITLE
경로당 이용률의 사회적 참여요소 대체 관련 의견

### ISSUE THREAD

**Issue by pear-c** [pwjdgus/Data_Analytics_for_Age_friendly_busan#102]
[중소도시 지역 거주 고령자의 경로당 프로그램 이용 실태 및 활용 전망](https://scienceon.kisti.re.kr/commons/util/originalView.do?cn=JAKO202110650792654&oCn=JAKO202110650792654&dbt=JAKO&journal=NJOU00580041) 결과에 따르면,
경로당을 이용하지 않는 고령자 중 경로당을 이용하지 않는 주된 이유로 '마땅히 즐길만한 활동이 없다'(43.5%) 인 것을 볼 수 있습니다.
뿐만 아니라, 경로당 이용자/비이용자들이 각각 생각한 활성화 방안 중 '다양한 프로그램 개발'(20.2%) / '프로그램의 다양화'(46.5%)로, 양 측 모두 프로그램의 다양화를 생각하였습니다.
이를 보았을 때, 사회적 참여 요소를 높였을 경우, 경로당 이용률의 증가를 기대해볼 수 있지 않을까 생각합니다.

**Comment by pwjdgus** [comment]
제가 요청한 의도와 같습니다.
