### ISSUE TITLE
높이 고저차 관련 의견

### ISSUE THREAD

**Issue by Kim-qjaJ** [pwjdgus/Data_Analytics_for_Age_friendly_busan#104]
https://contourmapcreator.urgr8.ch/
해당 사이트는 원하는 지역의 높이를 등고선 형태로 보여주는 사이트입니다.
경사로가 있는 거주 지역 같은 경우 지역의 높이 고저차를 고려한다면 조금이라도 합리적인 곳에 경로당을 설치 할 수 있다고 생각합니다.

**Comment by pwjdgus** [comment]
맞습니다 부산은 경사가 심한 길이 많아 꼭 필요해 보입니다. 구글의 고도 api와 osmnx를 통해 고도정보를 그래프에 적용 할 수 있는데 
이방법은 어떨까요?
