### ISSUE TITLE
거리에 관한 의견

### ISSUE THREAD

**Issue by Choiyuhyeon** [pwjdgus/Data_Analytics_for_Age_friendly_busan#105]
노인의 이동수단과 입지를 고려하였을때 걸어서 10분이내의 위치가 최적위치라는 것을 ppt내 설문조사 자료를 통해 기재해주셨습니다.
조금 더 상세한 거리단위가 필요할것 같습니다.
http://www.monews.co.kr/news/articleView.html?idxno=308356 
위 링크는 웨어러블 디바이스로 노인의 걸음걸이의 속도를 측정한 결과의 뉴스입니다. 
건강한 70대의 걸음걸이 평균속도는 1.23m/s이며 근감소증이 있는 노인분들은 1.12m/s입니다.
앞서 이슈에서 산소섭취량과 칼로리를 이용한 이동거리 관련한 좋은 의견과 이러한 정확한 거리척도를 조금 더 이용해서 GIS를 이용한 입지분석을 할때 도움이 되지 않을까 싶습니다.

**Comment by pwjdgus** [comment]
노인들의 걸음 속도를 반영하는 것은 괜찮은 아이디어 같습니다.

**Comment by dongchan0330** [comment]
좋은 의견인 것 같습니다. 10분 이내의 위치에 있다는 것을 고려하면 건강한 70대의 이동거리는 738m, 근감소증이 있으신 분은 672m로 66m 정도에 차이가 있기 때문에 노인들의 걸음 속도를 반영하는 것은 괜찮은 것 같습니다.
