### ISSUE TITLE
README.md 내용 추가

### ISSUE THREAD

**Issue by rvjst** [pwjdgus/Data_Analytics_for_Age_friendly_busan#107]
관련 용어에 현 프로젝트를 대입하여 수식으로 표현하는 것은 어떨까요?
ex) "행정 구 전체의 경로당의 위치 , 노인들의 밀집 지역 위치 및 자주 이동하는 구역 +  행정 구 전체 경로당 이용수 및 미래의 고령화 예측 결과 = 미래에 필요한 경로당의 수"

**Comment by pwjdgus** [comment]
직관적으로 이해 가능하겠네요
