### ISSUE TITLE
노인 여가생활 동향 분석에 관한 참고자료 추가

### ISSUE THREAD

**Issue by DongUk-Park** [pwjdgus/Data_Analytics_for_Age_friendly_busan#108]
노인 여가 활동 동향 분석에 관한 논문 자료입니다.
연령별, 취업 유무별, 군집 유형별 등 여가활동 참여 실태와 참여 시간등이 나와있습니다.
참고자료로 활용하면 좋을 것 같습니다.

(https://www.kihasa.re.kr/hswr/assets/pdf/792/journal-34-2-37.pdf)

**Comment by qkrxodnr** [comment]
참고자료로 좋은것 같습니다!
