### ISSUE TITLE
경로당 만족도에 대하여

### ISSUE THREAD

**Issue by tam31** [pwjdgus/Data_Analytics_for_Age_friendly_busan#110]
부산_경로당_이용률.csv 로드에서 이용률이 모두 15%이하로 나타내고 있어 기존 경로당의 만족도가 매우 낮은 것을 알 수 있습니다. 또한 현재 급속도로 증가하고 있는 고령화 사회이지만 '경로당의 운영 주체인 대한노인회 관계자는 "경로당 회원 수 현황을 공개할 수 없다"면서도 "(회원 수가) 예전만큼 늘고 있지는 않다"고 말했다.'라는 것을 유추해 본 결과 고령층들의 증가에 비해 경로당의 이용률은 증가하지 않은 것을 알 수 있었습니다.
그래서 경로당의 이용률을 높이기 위해 고령층들이 선호하는 리즈 등을 찾아 개선하는 것이 큰 효과가 있을 것이라 생각합니다.

**Comment by pwjdgus** [comment]
동의합니다
