### ISSUE TITLE
경로당 및 다양한 데이터에 대한 제언

### ISSUE THREAD

**Issue by hesuhesu** [pwjdgus/Data_Analytics_for_Age_friendly_busan#112]
경로당 관련 데이터와 자료에 대해서는 구체적으로 제시되지만 노인복지관, 노인교실 등 노인들의 교육 및 복지시설에 대해서 자료가 별로 없는거 같습니다. 
경로당에 한정되지 않는다면 다른 시설에 대해서도 지속적으로 다양한 데이터와 소스를 제시할 예정입니다. 
관리자의 생각은 어떤지 여쭙고 싶습니다.

**Comment by pwjdgus** [comment]
우선은 경로당에 대해 확실하게 하고 진행하는게 좋다 생각합니다.

대부분의 인원이 아직 프로젝트에 대해 코드리뷰가 안되었다 판단합니다. 또한 프로젝트 이해도 미흡하다 생각합니다.

현 상황에서 다른 시설에 대한 분석을 시작하기엔 무리가 있어보입니다.

하지만 노인복지시설 이라는 큰 틀에서 분석을 한다면 이야기는 달라질듯 합니다. 이때 현재 로직을 노인복지시설이라는 큰 범위에서 다시 생각을 해봐야겟지요.

추후 팀원이 만들어진다면 어느 한팀이 전담하여 하는 편이 어떨까요?

**Comment by hesuhesu** [comment]
우선 향후 방향을 디테일한 빌드에 기여함에 적극 동의합니다! 

현 프로젝트가 많은 개선이 된다면 전담팀을 짜도록 하겠습니다.  

자세한 리뷰 감사합니다!
