### ISSUE TITLE
경로당 이용률에 관한 이슈

### ISSUE THREAD

**Issue by gymdong** [pwjdgus/Data_Analytics_for_Age_friendly_busan#116]
자료에 의하면 경로당 이용률은 현재 발표자료에 사용된 2019년 시점까지는 지속적으로 감소하고 있는 것으로 나타났습니다. 그러나 제가 참고자료에 올린 2020년의 노인실태조사 보고서에 따르면 오히려 2020년은 코로나가 지나간 해임에도 불구하고 경로당 이용률이 오히려 상승하였음을 확인할 수 있습니다. 

이것의 요인에 대해 분석하면 

- 첫 번째, 코로나로 인해 만남이 적어진 노인들이 친목 도모를 위해 경로당을 더 많이 이용하게 되었음
- 두 번째, 2020년 조사에서는 취미여가 프로그램이나 건강서비스를 위한 이용의 비율이 점점 높아졌음

정도를 추측할 수 있습니다. 또한 이것은 이전에 비해 조금씩 높아지고 있는 노인들의 교육 수준과도 연관이 있는 것 같습니다. 교육 수준이 높고 동지역 거주 노인일수록 노인복지관을 이용하는 비율이 높았는데, (노인복지관은 경로당보다 취미여가, 건강서비스를 위해 이용하는 비율이 높음) 지금은 읍면부 지역의 노인들도 교육수준이 이전보다 높아졌기 때문에 읍면부 지역 경로당에서도 취미여가나 건강서비스를 찾는 비율이 높아진 것 같습니다.

그러므로 경로당 이용률을 올리기 위해서는 접근성에 더해 경로당의 콘텐츠를 늘리는 것도 중요한 것 같습니다. 콘텐츠에 관련해 조사하여 pull req 하면 괜찮을까요?

**Comment by pwjdgus** [comment]
네
