### ISSUE TITLE
부산 고령인구 증가 추세 파악 데이터 최신화

### ISSUE THREAD

**Issue by as1901as** [pwjdgus/Data_Analytics_for_Age_friendly_busan#117]
현재 2020년까지의 고령 인구 증가 데이터를 사용하고 있습니다. 2021년의 데이터를 추가해 데이터의 최신화가 필요해 보입니다.

추가될 내용---
부산-비율.csv
2021 원데이터 : 20.4
2021 전년 대비 증감 : 1.0

2021년도 데이터 추출, 시각화 코드 추가

**Comment by pwjdgus** [comment]
좋습니다
