### ISSUE TITLE
부산 인구 데이터 최신화

### ISSUE THREAD

**Issue by dainnnnn** [pwjdgus/Data_Analytics_for_Age_friendly_busan#118]
현재 올라와있는 부산 인구수 파일의 기준은 2015년입니다.
부산시의 인구 전입,전출이 크기 때문에 비교적 최신 데이터로 수정해야 한다고 생각합니다.

**Comment by pwjdgus** [comment]
그건..예측 평가를 위해서 사용한 데이터입니다.

2020년 인구현황 별도로 있습니다.

21년 사용하지 않은 이유는 당시에 21년 인구 데이터가 지속적으로 갱신되고 있었기 때문에 확실하게 정해진 데이터를 사용했습니다

**Comment by dainnnnn** [comment]
그럼 2020년 인구현황을 2021년 인구현황으로 수정해도 괜찮을까요?

**Comment by dainnnnn** [comment]
혹시 예측 평가를 위한 데이터를 2015년 기준으로 한 이유를 여쭤봐도 될까요??

**Comment by pwjdgus** [comment]
평가를 15년으로 했던이유는 딱히 없습니다

단, 15년기준 2030년 예측한 모델과 2020년 인구를 2030년 예측한 모델은 비교를 하기엔 무리가 있다 판단했습니다. 하여 15년 기준 21년을 예측한 것입니다.

즉, 과거에서 현재를 예측한 값과 현재를 비교한 것 입니다.

**Comment by dainnnnn** [comment]
넵!
