### ISSUE TITLE
milestone의 활성화를 제안합니다.

### ISSUE THREAD

**Issue by BlueArcticFox** [pwjdgus/Data_Analytics_for_Age_friendly_busan#122]
## 개요
많은 Issue가 올라오고 있으나 분류의 기준이 없어 불편함이 있습니다.
현재 프로젝트 단계에서 활발히 논의되고 있는 "고도에 따른 경사도를 입지선정에 반영"에 관해 milestone을 만들었으며, 존재하는 관련 이슈에 milestone을 추가해놓았습니다.
milestone 기능을 활용하여 불필요한 비용없이 해당 주제에 효율적으로 논의될 수 있도록 milestone의 활성화를 제안합니다.

[참고사이트](https://cyberx.tistory.com/112)

## 기대효과
- milestone을 활용하여 특정 목표에 부합한 issue를 손쉽게 찾고, 논의할 수 있습니다.
- milestone을 활용하여 프로젝트의 이정표를 설정하면, issues의 방향성을 잡기에 용이합니다.

**Comment by pwjdgus** [comment]
찬성입니다
