### ISSUE TITLE
변수 이름 통일과 old_people을 대체할 수 있는 단어 제안

### ISSUE THREAD

**Issue by MwaungMwaung** [pwjdgus/Data_Analytics_for_Age_friendly_busan#123]
Busan Senior Center(BSC)의 시급한 개선을 위한 입지 분석 모델 코드를 보면 어르신을 변수 명으로 칭할 때 old_people/senior_people 등으로 여러 이름으로 부르고 있습니다.
이를 elder(의미: 원로[장로]들, 어른들)라는 단어로 통일하면 언더바로 인해 변수 명이 복잡해지는 경우를 줄이고 코드의 통일성을 향상시킬 수 있을 것 같습니다.
(before) df_senior_people = get_senior_people_by_admin_area(district)
(after) df_elder = get_elder_by_admin_area(district)

**Comment by pwjdgus** [comment]
변수명이 변경된 별도의 코드 파일 한번 만들어 보는게 좋을 것 같네요
