### ISSUE TITLE
경로당 이용률 관련 의견

### ISSUE THREAD

**Issue by Syunoh** [pwjdgus/Data_Analytics_for_Age_friendly_busan#125]
미래 증설할 경로당의 수는 증가할 고령인구 수를 바탕으로 나오고 있습니다.
현재 적절한 경로당의 수를 파악할 때 사용되는 경로당 이용자 비율은 현재를 기점으로 계산하기 때문에 증설할 경로당의 수에 적합하지 않습니다. 미래에 사용될 경로당의 이용자 비율을 예측해서 증설할 경로당의 수에 대입한다면 더 정확한 값이 나올 것이라고 생각합니다.
따라서 앞으로의 경로당 이용률을 과거와 비교하여 예측할 수 있게 만드는 것도 괜찮을 것이라 생각됩니다.

**Comment by pwjdgus** [comment]
이용률을 예측하기엔 샘플이 부족합니다
