### ISSUE TITLE
입지요건 선정에 필요한 편의시설 데이터 추가

### ISSUE THREAD

**Issue by WaiCat** [pwjdgus/Data_Analytics_for_Age_friendly_busan#128]
최적의 입지요건 선정에 인구수와 거리만으로는 부족할거 같아 병원, 무료급식소등의 편의시설 데이터도 반영해야 할거 같습니다.';
#127

**Comment by pwjdgus** [comment]
구체적으로 어떤식으로 반영할 계획이신지

**Comment by WaiCat** [comment]
도보 기준 네트워크 중심성 및 이동시간에 따른 영역 시각화자료를 보고 거리에 따른 경로당 위치 선전을 할때 각종 편의 시설의 위치를 점(.)등으로 시각화하여 입지 선정에 반영할 계획입니다.

**Comment by pwjdgus** [comment]
단순히 주변에 다른시설이 있는다 표시인가요?

**Comment by yujinn00** [comment]
인구수 뿐만 아니라 편의 시설의 거리도 교집합하여 최적의 경로당 입지 선정을 추구할 것입니다.

**Comment by pwjdgus** [comment]
우선, 큰 틀을 잡고 고려하는 방향으로 합시다!
