### ISSUE TITLE
경로당 입지분석 추가 요소

### ISSUE THREAD

**Issue by as1901as** [pwjdgus/Data_Analytics_for_Age_friendly_busan#129]
현재 경로당 입지 분석에 이동 거리 만을 고려하고 있는데 주변에 노인복지관, 노인교실 등의 여부도 함께 고려하면 더 좋은 입지 분석이 될 것 같습니다.

추가 할 데이터-----
[부산광역시_노인교실 현황_20210831.csv]
[부산광역시_노인복지관 현황_20220101.csv]

**Comment by pwjdgus** [comment]
경로당의 위치와 주변에 복지시설간의 관계(?)를 어떤식으로 표현 할 계획인가요

**Comment by as1901as** [comment]
현재 시각화 데이터에서 노란색 점으로 된 부분이 최적의 입지라면 여기서 복지 시설과의 거리가 더 가까운 쪽으로 범위를 더 좁힐 수 있을 거 같습니다.

**Comment by pwjdgus** [comment]
현재 다른 복지시설의 위치가 미래에도 같다는 가정인가요?

**Comment by as1901as** [comment]
네 맞습니다.

**Comment by pwjdgus** [comment]
우선 시설 관련 여부는 한번 고민해보는 것으로 합시다.
