### ISSUE TITLE
경로당 입지조건 고려요소 추가

### ISSUE THREAD

**Issue by dainnnnn** [pwjdgus/Data_Analytics_for_Age_friendly_busan#130]
현재 입지분석의 접근성은 도보 이동시간으로 되어있습니다.
경로당 마다 진행되는 프로그램이 다를 수 있고, 노인분들의 좀 더 다양한 여가 활동을 위해 경로당 간의 교류도 있을 수 있습니다.
거동이 불편하신 분들은 가까운 위치에 있는 것이 가장 좋지만, 비교적 정정하신 분들을 위해 혹은 경로당으로 교육이나 봉사를 오시는 분들 등을 위해 버스정류장을 입지조건 고려요소로 추가해도 괜찮다고 생각합니다.

추가할 자료
부산시_노선별_정류소위치.csv

**Comment by pwjdgus** [comment]
비슷한 의견이 있었는데 추후에 논의 해봅시다.
