### ISSUE TITLE
경로당 이용률에대한 관련 의견

### ISSUE THREAD

**Issue by FarmingWon** [pwjdgus/Data_Analytics_for_Age_friendly_busan#132]
현재 경로당은 노인들 중에서도 80대 이상의 노인들이 주로 경로당을 이용한다는 자료가 있습니다.

2017년 보건사회연구원이 실시한 노인실태조사에서 경로당 이용률은 전국 평균 19.2%에 불과했다. 지역으로 나눠볼 때 읍면지역은 40.1%였지만, 도시지역의 동 지역은 10.3%로 떨어졌다. 즉, 도시지역 노인은 10명 중 1명만 경로당을 이용하는 셈이다.
이용자 연령도 80세 이상이 약 80%(79.4%)를 차지해, 주로 80대 이상 후기고령노인들이 경로당을 이용하는 것으로 나타났다.

그러므로 경로당 입지를 고려할 때 노인의 기준을 80대 이상으로 한 뒤 데이터를 분석하는 방법이 최적의 경로당 입지를 탐색할때 도움될 것 같습니다.

**Comment by pwjdgus** [comment]
의견 고맙습니다
생각을 달리하면 입지 제시에 고려되는 접근성, 이용률이 높아져 다양한 나이의 고령자들이 이용을 한다면 꼭 80대 이상으로 분석할 필요는 없다 생각합니다.

또한, 80대 이상을 기준으로 했을 경우 예를 들어 10년 뒤 모두 사망할 가능성도 높은 듯 합니다...
