### ISSUE TITLE
노인복지시설 고려 요소 추가 의견

### ISSUE THREAD

**Issue by TAEYOUNGY00N** [pwjdgus/Data_Analytics_for_Age_friendly_busan#133]
![1인 노인가구](https://user-images.githubusercontent.com/100738656/163107276-230155c4-4eca-4617-8065-8b2407c344ff.png)

1인 노인 가구의 추이와 전망 입니다. 1인 노인 가구의 경우 복지시설의 필요성이 더 높고 효율성이 좋다고 생각합니다. 
1인 노인 가구까지 고려하는 건 어떻게 생각하시나요?

**Comment by pwjdgus** [comment]
전체 노인인구로 했디 때문에 1인가구 포함됨이 아닐까요?

**Comment by TAEYOUNGY00N** [comment]
노인 1인 가구가 많은 구역에 우선순위를 높여주거나 시설 증설을 생각했습니다

**Comment by pwjdgus** [comment]
혹시 최근의 통계자료를 알고 싶은데 있을까요?

현자료는 2014년으로 보입니다

**Comment by pwjdgus** [comment]
2017년 이후 수치는 예측값인가요?

**Comment by TAEYOUNGY00N** [comment]
네 2017년이 가장 최근으로 보입니다.

**Comment by pwjdgus** [comment]
알겠습니다. 추후 고려해보는 방향으로 가봅시다.
