### ISSUE TITLE
경로당 입지 선정 기준 추가

### ISSUE THREAD

**Issue by k69121** [pwjdgus/Data_Analytics_for_Age_friendly_busan#134]
고령 인구의 접근성을 고려해서 버스, 지하철이 많은 교차로 위주로 경로당을 설치하면 좋을거같습니다.  osmnx를 이용하여 교차로쪽에 가중치를 주도록 할수있습니다.

# osmnx 란?
OpenStreetMap에서 지리 공간 데이터를 다운로드하고 실제 거리 네트워크 및 기타 지리 공간 기하학을 모델링, 프로젝트, 시각화 및 분석할 수 있는 Python 패키지입니다. 한 줄의 Python 코드로 걷기, 운전 또는 자전거 타기 가능한 도시 네트워크를 다운로드하고 모델링한 다음 쉽게 분석하고 시각화할 수 있습니다. 다른 인프라 유형, 편의 시설/관심 지점, 건물 발자국, 고도 데이터, 도로 방향/방향, 속도/이동 시간을 쉽게 다운로드하여 작업할 수 있습니다.

**Comment by Choiyuhyeon** [comment]
접근성이 좋아질 것 같아 좋은 아이디어 같습니다. osmnx도 입지분석을 할때 정말 유용할것 같습니다.

**Comment by pwjdgus** [comment]
많은 정도가 어느 정도인가요?

**Comment by k69121** [comment]
아니면 정류장 데이터를 가져와서 지도상에 뿌리고 정류장과 가까운쪽으로 경로당을 짓는것이 좋을거같습니다.

**Comment by k69121** [comment]
물론 미래에 정류장, 지하철 위치가 바뀔수있다는 변수가 존재하지만 그부분은 현재로선 교려하지않아도 될거같아요. 그떄는 교통부랑 상의해서 미래에 추가적으로 지을 정류장의 데이토를 가지고 오면되는것이니 지금으로선 현재의 데이터를 활용하죠

**Comment by pwjdgus** [comment]
'가깝다'는 기준은 사람마다 차이가 있을 거라 정확한 기준이 필요해 보입니다

**Comment by k69121** [comment]
넵 그럼 버스 정류장 기준으로도 도보 5분 10분 이내거리를 적용하는게 좋을거같습니다.

**Comment by pwjdgus** [comment]
5분 10분 거리에 대해 적용하는 적절한 근거나, 사유가 있다면 정당하게 사용 가능해 보입니다

**Comment by k69121** [comment]
경로당 입지를 선택할떄 필연적으로 거리가 애매하신분들이 생겨날수밖에없습니다. 그러신분들은 주로 버스같은 교통수단을 사용합니다. 보도로 장거리 이동을 하기위해서는 나이떄문에 횡단보도같은곳에서의 사고 확률이 높아지기떄문이죠 
[노인 교통수단](https://kosis.kr/statHtml/statHtml.do?orgId=711&tblId=DT_71105_16_F16)
위 자료로도 알수있듯이 도보보다는 버스같은 대중교통을 선호하는걸 알수있습니다.

**Comment by pwjdgus** [comment]
그래서 최종적으로 말하고 싶은 의견이 뭔가요?
