### ISSUE TITLE
최적 입지 문제점

### ISSUE THREAD

**Issue by hhhhmang** [pwjdgus/Data_Analytics_for_Age_friendly_busan#135]
부산의 지형을 생각하지 않고 입지시설을 고려하는 것은 잘못 됐다고 생각합니다.
부산의 경우 저지대에 위치한 경로당은 비만 오면 침수 피해를 입는다고 합니다. 내부에는 곰팡이가 심하게 슬어 미관을 해치는 것은 물론 악취까지 풍긴다고 합니다. 그에 따라 경로당 이용률도 좋지 않을 것으로 예상됩니다.

따라서 이동수단과 이동거리로만 최적의 입지시설을 선정하는 것에는 문제점이 있다고 판단됩니다.

**Comment by hhhhmang** [comment]
추가적으로 초고령화 도시 부산의 주민들은 경로당을 "혐오시설"로 인식하고 있다고 합니다.
주변 상황을 고려하지 않은 경로당 설치는 주민들의 불만을 호소한다고 합니다.
(노인들의 고성방가와 음주에 의함)

**Comment by pwjdgus** [comment]
정성적인 변수인듯 한데 구체적으로 계획이 있는지 알고싶군요

**Comment by hhhhmang** [comment]
@pwjdgus 수식화 할 수 있을지 생각해보겠습니다.

**Comment by pwjdgus** [comment]
하나 궁금한게 부산 초점을 둬서 만들면 만약 다른 지역에 대한 입지 제시는 불가능 하겠네요?

**Comment by pwjdgus** [comment]
아이디어는 좋으나 넓은 범위로 생각해본다면 좁은 의미의 변수 고려는 좋지 않아 보입니다. 
>부산의 경우 저지대에 위치한 경로당은 비만 오면 침수 피해를 입는다고 합니다. 내부에는 곰팡이가 심하게 슬어 미관을 해치는 것은 물론 악취까지 풍긴다고 합니다. 그에 따라 경로당 이용률도 좋지 않을 것으로 예상됩니다.  

이것을 넓게 생각해본다면 고도를 고려하는게 바람직 하지 않을까요?

**Comment by hhhhmang** [comment]
@pwjdgus 의견 감사합니다! 참고하겠습니다.
