### ISSUE TITLE
권역에 따른 입지선정

### ISSUE THREAD

**Issue by Choiyuhyeon** [pwjdgus/Data_Analytics_for_Age_friendly_busan#136]
현재 노인복지시설에 관해서 입지분석을 하는 도중에 경로당을 중심으로 이야기가 되는것 같아서 의문점이 들었습니다.
노인복지시설의 종류는 경로당 뿐 아니라 권역에 따라서도 이와 같이 여러가지로 나누어집니다.
-1차권역 : 경로당,노인교실,보호서비스 등
-2차권역 : 양로시설,요양시설 등
-3차권역 : 노인복지관,노인전문병원 등
현재 입지선정에 관해서 정말 좋은 아이디어들이 나오고 있는거 같은데요, 경로당의 입지분석 말고도 권역에 따른 다른 노인복지시설들도 같은 방법으로 입지선정을 하면 좋을것 같습니다.

**Comment by pwjdgus** [comment]
권역에 따른 입지 예시가 있을까요 이해가 잘 안되네요 ..

**Comment by Choiyuhyeon** [comment]
![캡처](https://user-images.githubusercontent.com/100738360/163136101-cb9c395b-558e-44ab-b03a-62004d5c74c4.PNG)
위 내용은 인천시에서 gis를 이용한 노인센터 입지선정을한 자료입니다. 이러한 방식으로 권역을 나누어서 입지선정을 하면 접근성이 좋은 또 다른 노인복지시설들도 입지선정을 하는데 도움이 될 것이라 생각합니다.

**Comment by pwjdgus** [comment]
접근성에 여러 의견이 나오고 있으니 추후 자세한 논의를 통해 결정합시다!
