### ISSUE TITLE
미래 고령인구 예측 데이터에 관한 제의

### ISSUE THREAD

**Issue by BlueArcticFox** [pwjdgus/Data_Analytics_for_Age_friendly_busan#139]
## 미래 고령인구 예측 데이터에 관한 제의
#85 을 참고하여 제의드립니다.
대한민국 정부의 통계청에서 예측한 미래 고령인구(2070년까지)에 관한 데이터셋이 존재합니다. [사이트](https://kosis.kr/visual/populationKorea/PopulationByNumber/PopulationByNumberMain.do?mb=N)
기존의 이를 활용하면 기존의 미래인구 예측 수식에 비해 신뢰성 면에서 효과를 볼 수 있을 것 입니다.
<hr>

위의 issue에서도 @pwjdgus 님이 코멘트 하셨듯이 시단위로 인구를 예측하기 위한 방법을 말씀하셨는데, 위 사이트에서 고령인구 시도별 구성비의 데이터를 통해 2047년까지의 부산광역시 고령인구 통계 데이터를 확인할 수 있었습니다.
- 주요_연령계층별_추계인구_생산연령인구__고령인구_등__시도_20220413203931.csv
여기서 행정시 단위, 행정동 단위로 인구를 나누려면 현재의 시, 동단위 인구 비율을 통해 미래에 급진적인 인구 이동이 없을 것으로 가정하고 계산 할 수 있을 것입니다.
ex) 행정시.동 단위 고령인구 = 부산광역시 고령인구 * 행정시.동 인구 비율(%)
<hr>

비록 2047년까지의 데이터 뿐이지만 이정도로 충분할 것으로 생각되며, 이후의 데이터가 더 필요할 경우 시도별 인구비 예측 데이터가 있다면 이와 함께 미래 고령인구(2070년까지) 통계 데이터를 활용하여 신뢰성 높은 다른 예측 수식을 만들 수 있을 것 입니다.
(위의 사이트에서도 시도별 인구비 예측 데이터가 있으나 2047년까지의 예측 통계 뿐입니다.)
ex) 해당년도 부산광역시  고령인구 = 전국 고령인구 * 부산광역시 인구 비율(%)
<hr>

**위의 수식은 단순한 수식이며 더 고려할 사항이 있을 수도 있습니다.**

**Comment by pwjdgus** [comment]
좋은 생각인듯 합니다.

한가지 우려되는 부분이 있습니다. 
미래인구 예측수식 마저 데이터를 활용하여 사용 했을 경우

**프로젝트의 core기술이 없다고 생각합니다.**(프로젝트 당시에도 미래 인구 데이터가 존재하는 것은 알고 있었습니다.)

만약 인구 예측을 데이터로 사용한다면 다른 어딘가를 핵심으로 둬야할 방법론이 필요해 보입니다.

예를 들어, 고도를 고려한 경로당 접근성, 이용률에 대한 다른 접근 등

**Comment by BlueArcticFox** [comment]
프로젝트 소개에서도 말씀하셔주셨듯이 현 인구예측 수식은 불안정한 부분이 많으며 고도화의 필요성을 언급하셨습니다.
실제로 미래 고령인구의 예측을 할 때 과거의 데이터의 증감율을 통해 평균증감율로 미래를 예측하는것 뿐 아니라 매년 출산율이 다르기에 _(특히 90년대 후반 전과 비교하여 출산율이 급증하였고 그 이후 낮아지는 양상을 보였습니다)_ 매년 고령인구의 범위에 들어가는 인구의 수에 차이가 있을 것이며 사망률 또한 고려하여야 할 사항일 것입니다.
<hr>

그렇기에 현 단계에서는 인구예측자체가 저희 프로젝트의 core기술이 아니라고 생각했습니다.
그렇기에 통계청의 데이터를 통해 수식 고도화에 드는 비용을 줄이고, 신뢰성은 높이고, core기술을 개발하기 위해 그 비용을 집중시키는 것이 바람직하다 생각됩니다.

**Comment by pwjdgus** [comment]
보통 인구 예측에 따른 값은 통계자료를 만든이들의 시나리오에 따라 만들어진 수식을 통한 값입니다.

(자료를 더 찾아본다면 미래 인구 값이 자료마다 다른걸 알 수 있습니다.)

통계자료 사용하는게 나쁘다는건 아닙니다.

제가 우려하는 부분은 통계 데이터 의존시 자유롭지 못 하다는 점입니다. 이점은 생각해보십시요

주제가 주제인만큼 고령인구는 중요합니다.

데이터가 몇년도 부터 제공되는지 모르겠지만 모델을 만든 후, 평가시에 비교를 할 수 있을지도 생각바랍니다.!!

**Comment by BlueArcticFox** [comment]
지금 현 단계에서는 늘어가는 고령인구에 대한 경로당 추가의 필요성, 그리고 그의 입지선정을 위한 수식으로는 충분해 보이지만, 고도에 따른 이동거리 계산과 같이 좀 더 프로젝트가 발전 된다면 주제가 주제인 만큼 미래의 고령인구 예측 자체의 중요성이 더욱 대두 될 것이라 생각했습니다.

그렇기에 수식의 고도화는 현 단계에서는 고려하지 않고 신뢰도 있는 통계자료를 활용해보고 다른 부분의 발전이 이루어 진 후에 고도화된 수식이 정립된다면 그때서야 확장해보는 것이 어떨까 싶었습니다.

하지만 말씀하신대로 확실히 차후 확장성을 생각하고 자유로운 개발을 위해선 저희만의 수식을 정립하여 다른 조직의 시나리오에 따라가는 것이 아닌 과거의 확실한 데이터를 통해 저희 프로젝트 만의 시나리오를 만들어 가는 것이 훨씬 용이해 보입니다.
