### ISSUE TITLE
다른 건물의 위치를 고려한 경로당 위치 의견

### ISSUE THREAD

**Issue by pear-c** [pwjdgus/Data_Analytics_for_Age_friendly_busan#140]
본문에서 구한 후보지 네트워크를 바탕으로 경로당의 최적 입지를 구하려 할 때, 실질적으로 그곳이 경로당을 지을 수 있는 위치인가도 고려해야한다고 생각했습니다.
이 점에서, [도로명주소 데이터](https://www.juso.go.kr/addrlink/addressBuildDevNew.do?menu=mainJusoDb)를 사용하면 기존 건물의 존재 유무를 알 수 있으니 후보지 내 건물들의 위치를 나타내고, 이동거리에 따른 최적입지와 합치면 실질적인 경로당 지을 위치를 알 수 있지 않을까 생각했는데 막연한 생각인건지 궁금합니다.

**Comment by pwjdgus** [comment]
물론 지을 수 있는 위치인가 고려하는게 맞다 생각할 수 있는데

입지 제시니까 경로당 설치에 대한 선택은 사용자에게 있겠지요
