### ISSUE TITLE
코드 챕터 관련질문

### ISSUE THREAD

**Issue by leeseungmin-kr** [pwjdgus/Data_Analytics_for_Age_friendly_busan#143]
행정 동 단위 필요한 경로당 수랑 행정 동 단위 적절한 경로당수 산출이랑 
다른점이 뭔가요?

**Comment by DongUk-Park** [comment]
필요한 경로당 수 = 적정 경로당 수 - 현재 경로당 수 인 것 같습니다.
질문에 알맞는 대답이 맞을까요 ?

**Comment by DongUk-Park** [comment]
필요한 경로당 수 = 적절한 경로당 수 - 기존에 설치된 경로당 수 입니다.
질문에 알맞은 대답이 맞을까요?

**Comment by leeseungmin-kr** [comment]
넵 감사합니다 ㅎㅎ

**Comment by leeseungmin-kr** [comment]
문제 해결!
