### ISSUE TITLE
경로당 규격이 상이함에 따른 단위 구별 필요 제기

### ISSUE THREAD

**Issue by MMIINNNN** [pwjdgus/Data_Analytics_for_Age_friendly_busan#145]
![화면 캡처 2022-04-14 020129](https://user-images.githubusercontent.com/100738705/163233692-d8a07483-d69c-4df4-a7de-c837b46d05e4.png)

위 표를 보시면 '적절한 경로당 수'를 산출한 뒤 현재 '경로당 수'와 비교한 후 '필요한 경로당 수'를 산출합니다.
하지만 기존에 있는 경로당은 각각 규격이 상이하고,  이용이 원활한지 혼잡한지 판단이 어렵기 때문에
기존의 '경로당 수'의 1 단위와  '필요한 경로당 수'의 1 단위는 같다고 볼 수 없다고 생각합니다.

따라서, 두 자료의 수치가 같더라도 단위가 다름을 명시하는 것을 제안드리고
 '필요한 경로당 수' 즉, 지어야 할 경로당의 규격을 임의로 설정, 통일하는 것을 제안드립니다.

**Comment by pwjdgus** [comment]
어짜피 경로당의 최소 규모는 동일하다 판단했습니다

**Comment by BlueArcticFox** [comment]
"기존의 경로당 수"와 "필요 경로당 수"의 단위가 다르다고 하셨는데 해당 결과 산출메서드의 과정을 보면 행정동 단위의 이용률과 고령인구 비율에 따른 경로당 수를 계산하였습니다.

이용률과 인원에 따른 기존 경로당 수의 단위는 평균으로 계산이 되었으며, 필요 경로당 수는 기존 경로당 수의 단위에 따라 산출되었으므로 행정동 단위의 "기존 경로당 수"와 "필요 경로당 수"의 단위는 같다고 보아야 한다고 생각됩니다.
<hr>

물론 다른 두 행정동을 경로당의 수로 비교하기에는 산출된 단위가 다르기에 부적절한 것이 맞습니다만 같은 행정동에서 기존과 필요 경로당 수를 비교하는 것에는 문제가 없을 것으로 생각됩니다.

**Comment by MMIINNNN** [comment]
자세한 리뷰 감사합니다 :)
