### ISSUE TITLE
지역별 경로당 & 복지시설 현황을 지도로 검색하기 가장 좋은 포털사이트

### ISSUE THREAD

**Issue by sj2305** [pwjdgus/Data_Analytics_for_Age_friendly_busan#147]
각 포털 사이트(네이버, 카카오맵, 구글)에서 지역별 경로당 & 복지시설 현황을 지도로 검색해봤는데
이들 중 **카카오맵**이 가장 정확하고 다양하게 나오는 것 같습니다.

[지역이름] [노인복지]
[지역이름] [경로당]
이 형태로 검색해 보시면 됩니다.

검색 내용 외에도 다양한 연관내용이 같이 검색된다는것이 가장 큰 특징인 것 같습니다.

검색 내용만 포함시키고 싶을땐 **구글지도**가 더 나을 수도 있습니다.

입지선정 & 분석 시 조금이나마 도움이 되셨으면 좋겠습니다.

https://map.kakao.com/

**Comment by BlueArcticFox** [comment]
도움이 되는 자료나 사이트에 관한 정보는 wiki에 페이지를 만들어 운영하는것이 어떨까 싶습니다.

**Comment by sj2305** [comment]
> 도움이 되는 자료나 사이트에 관한 정보는 wiki에 페이지를 만들어 운영하는것이 어떨까 싶습니다.
자세히 알아본 결과, 보통 각종 위키(나무위키, 위키피디아 등)의 초반 부분엔 해당 주제에 대한 전반적인 개요가 가장 먼저 나오고 그 외엔 간단한 관련 용어들을 정리해 놓는것이 일반적이었습니다.

다른 저장소들도 그렇게 관리되고 있는 부분입니다.

아니면 참고자료인 만큼 code 페이지의 참고자료 폴더에 해당 내용을 추가해 보는건 어떨까요?

**Comment by BlueArcticFox** [comment]
참고자료에 사이트 주소를 등록하기에는 따로 md파일을 생성하게 될 것이고, 열람할때도 md파일을 연 후 사이트에 접속하게 되니 접근성이 떨어질 것 같습니다.

그렇기에 Readme.md 파일에 참고사이트가 개시되어있는데 code에 올리시려면 그쪽에 추가하는 것이 좋을 것 같습니다.

Wiki를 제안드린건 wiki의 활성화와 더불어 Readme파일이 너무 길어지큰 것을 막기위한 목적
그리고, main에 commit하려면 권한면문제나 Pull request등 과정이 필요하지만 wiki에는 누구나 편집할 수 있으니 편집의 편의성과 readme 파일처럼 따로 열어보지 않고 바로 사이트에 접근 할 수 있다고 생각했습니다.

**Comment by sj2305** [comment]
답변 주신 의견을 반영하여 Readme 파일의 국내 참고자료 헤더 부분에 해당 내용을 추가하였습니다.
참고내용인 만큼 위키보단 Readme부분에 추가하는것이 더 좋겠다고 판단했기 때문입니다.

또 다른 의견 있으시면 언제든지 답변해주세요. 
감사합니다.
