### ISSUE TITLE
노인의 범위의 모호함과 노인의 이동거리의 상관관계

### ISSUE THREAD

**Issue by leeseungmin-kr** [pwjdgus/Data_Analytics_for_Age_friendly_busan#149]
노인들 중에서도 거동이 불편한사람이나, 장애인, 남/녀 에 대한 값은 포함하지 못한거 같은데,
위에 언급한 내용의 값도 같이 포함되면 좋을거같습니다.

https://www.koreascience.or.kr/article/CFKO200311922150080.pdf

5페이지에 보면 보행속도에 대한 연구자료결과가 있습니다.

**Comment by pwjdgus** [comment]
어떻게 포함하면 좋을까요

**Comment by leeseungmin-kr** [comment]
남, 녀로만 구분을 먼저 한다. 
그리고 남녀에 대한 이동속도를 위에 자료를 통해 수식을 만들어서 대입해본다. 
그리고 이동거리에 대한 그래프를 다시 수정한다.
n1= 남자
n2= 여성

(남성이동속도*n1+여성이동속도*n2)/(n1+n2)

 그리고 장애인이나, 거동이 불편하신 분들은 위의 식에서 값을 빼주고 따로 카태고리를 만들어주고 나중에 필요한 경로당 수에 더해주면 될거같습니다.
