### ISSUE TITLE
경로당 규격,경로당 등록자 수와 이용률 간의 상관관계

### ISSUE THREAD

**Issue by MMIINNNN** [pwjdgus/Data_Analytics_for_Age_friendly_busan#150]
1개 소의 경로당마다 등록자 수가 굉장히 상이한 것을 확인하고, 경로당마다 원활한 곳이 있고 혼잡한 곳이 있지 않을까하는 생각이 들었습니다. 그리고 이는 경로당 이용률에 영향을 준다고 판단했습니다.

n명의 경로당 등록자를 수용하기 위한 적절한 경로당 규격을 조사,산출하고 이용률과의 상관관계를 파악하는 것이 이용률 지표의 정확성을 높이고 현재 저조한 이용률을 해결하는 데에 도움이 될 것 같습니다.

**Comment by pwjdgus** [comment]
경로당 설치 규정에 따르면 최소 20명 이상 수용 가능한 시설이라 정하고 있습니다.
