### ISSUE TITLE
main branch README.md 국내 참고자료 중복

### ISSUE THREAD

**Issue by yujinn00** [pwjdgus/Data_Analytics_for_Age_friendly_busan#151]
대한적십자 무료급식소 데이터[[Link]](https://www.data.go.kr/data/15013107/standard.do)
부산광역시_종합병원 현황[[Link]](https://www.data.go.kr/data/15083386/fileData.do)
부산광역시_행정안전부 약국[[Link]](https://www.data.go.kr/data/15045036/fileData.do)

위의 3개와 아래의 3개의 데이터 링크가 중복이어서 위의 3개를 제거해야 할 것 같습니다.

무료급식소 표준 데이터
부산광역시_종합병원 현황
부산광역시_행정안전부 약국

**Comment by pwjdgus** [comment]
발견시 pull req하면 됩니다.
