### ISSUE TITLE
고도관련 osmnx 질문이 있습니다.

### ISSUE THREAD

**Issue by BlueArcticFox** [pwjdgus/Data_Analytics_for_Age_friendly_busan#156]
질문드립니다!

#104 코멘트의 의미가 osmnx의 osmnx.elevation.add_node_elevations_google() 함수를 통해 구글 고도 api로 그래프에 고도 속성을 부여하는 방식을 말씀하시는 건지 알고싶습니다.

만약 그렇다면 google maps의 api key가 있어야한다고 하는데, 공개적인 프로젝트에 api key를 노출시키는 것이 문제가 없는지 알고 싶습니다.

더불어 혹시 해당 프로젝트용으로 이미 발급된 api key가 있는지도 알고 싶습니다.

**Comment by pwjdgus** [comment]
>https://github.com/pwjdgus/Data_Analytics_for_Age_friendly_busan/issues/104 코멘트의 의미가 osmnx의 osmnx.elevation.add_node_elevations_google() 함수를 통해 구글 고도 api로 그래프에 고도 속성을 부여하는 방식을 말씀하시는 건지 알고싶습니다.  

맞습니다. osmnx에 관련 메서드 존재합니다.

api 키 제한 사항 설정이 가능한 것으로 압니다.(작년에 시도하려 했으나 포기) 

* 추후에 해당 repo는 private로 변경된다고 알고 있습니다.

**Comment by BlueArcticFox** [comment]
답변 감사합니다. 그럼 올해에 고도 관련한 진척이 있을 경우 프로젝트용으로 api key를 발급받을 계획이 있나요??

**Comment by pwjdgus** [comment]
추가적으로 OpenStreepMap에서 만든 elevation api가 있는데 경제적인 이유로 현재는 작동을 안합니다 ...

**Comment by BlueArcticFox** [comment]
아 그럼 개인으로 발급해서 실습을 해보는 식으로 해보겠습니다.
감사합니다.
