### ISSUE TITLE
노인 1명당 필요한 경로당 수 수식 관련 질문

### ISSUE THREAD

**Issue by as1901as** [pwjdgus/Data_Analytics_for_Age_friendly_busan#161]
현재 수식으로는 기장군과 강서구가 노인 1명당 필요한 경로당의 개수가 가장 높습니다.

그런데 중구를 예를들면 전체 노인 중 경로당 이용 비율이 위의 두 군에 비해 12.5%로 (기장:37.1 강서:38.2) 20% 이상 낮지만 경로당 1개소 당 등록자 수가 10명 이상 많습니다.

정리하면
중구는 기장군과 강서구에 비해 전체 노인의 인구 중 적은 비율의 노인이 경로당을 사용하지만 1개소당 노인 등록자 수는 많다 로 해석이 되는데

노인 1명당 필요한 경로당의 수를 생각해보면
전체 노인 중 적은 비율이지만 경로당에 인원이 몰리는 지역의 노인이 경로당을 더 필요로 하지 않을까 생각하는데 (인원 몰림 해소, 경로당 이용 비율 증가) 수식을 수정할 필요가 있는지 아니면 제가 놓치거나 생각을 잘못한 부분인지 질문 드립니다.

**Comment by pwjdgus** [comment]
질문을 잘 이해했는지 모르겠습니다.

우선 중구의 경우 고령 인구가 가장 적습니다. 경로당 수 또한 마찬가지 입니다.
 
이 부분이랑 연관 있지 않을까요?
