### ISSUE TITLE
Wiki는 어떤식으로 활용하는건지 궁금합니다.

### ISSUE THREAD

**Issue by OSSnewb** [pwjdgus/Data_Analytics_for_Age_friendly_busan#163]
말 그대로 프로젝트 관련 용어들의 사전적 의미를 정리해 놓는 공간인가요?

**Comment by BlueArcticFox** [comment]
아직 wiki의 활용방향성을 제대로 정립되지 않았습니다.
저는 프로젝트 인원들의 이해를 돕기 위해 관련 용어와 참고 사이트를 정리하고 싶습니다만, 프로젝트원과의 논의를 통해 wiki활용의 방향성을 논의해봐야 할 것 같습니다.

참고 사이트같은경우는 readme에 있고, 참고 자료는 참고 자료 폴더에 있고, 용어도 readme와 wiki에 동시에 있는데, 이렇게 계속 추가되면 readme 내용의 양이 비대해 질 것 같아 readme의 부수적인 정보를 wiki로 옮기고 프로젝트의 방향성과 핵심정보 위주로 readme에 집중시켜놓는 것이 어떨까 싶습니다.
