### ISSUE TITLE
입지선정 고려 사항 의견

### ISSUE THREAD

**Issue by TAEYOUNGY00N** [pwjdgus/Data_Analytics_for_Age_friendly_busan#164]
![2015미등록](https://user-images.githubusercontent.com/100738656/163425844-484b6a1d-d918-41e8-9421-c7318ad9ab3f.jpg)

경로당의 현황을 보다가 미등록 경로당의 문제를 보고 의견을 생각 해보았습니다.
[관련기사 1](http://www.knn.co.kr/181167)
[ 2 ](https://news.jtbc.joins.com/article/article.aspx?news_id=NB11347015)

입지 선정 조건에서 지역 당 현재 미등록 경로당의 수를 고려해 열악한 미등록 경로당을 우선 선정 조건으로 한다 거나 
그 주변 지역에 우선순위를 주는 것도 좋은 생각일 것 같습니다.

**Comment by pwjdgus** [comment]
혹시 최근의 자료는 없을까요?

**Comment by TAEYOUNGY00N** [comment]
[2022년](https://www.bsseogu.go.kr/ceo/index.bsseogu?menuCd=DOM_000000902002002000l)

현재 2022년 현황자료 중 미등록 여부가 함께 있는 지역은 아직 서구만 있는 것으로 보입니다.

**Comment by pwjdgus** [comment]
음,, 자료를 읽어보니 기존 경로당 설치 규정 미달인 시설이 미등록 처리가 되더군요

제 생각에는 미등록 경로당은 논외로 생각합니다.

저희가 도출한 좋은 입지 => 이용률, 접근성, 고령인구 밀집도를 모두 만족한 시설이라고 생각한다면, 미등록 경로당이 오히려 줄지 않을까요?

**Comment by TAEYOUNGY00N** [comment]
그렇게 판단해도 좋을 것 같습니다. 의견 감사합니다.
