### ISSUE TITLE
참고자료.md 링크 오류

### ISSUE THREAD

**Issue by hesuhesu** [pwjdgus/Data_Analytics_for_Age_friendly_busan#165]
[경로당 서비스 질에 따른 만족도](http://kangnam.dcollection.net/public_resource/pdf/000002049854_20220412230801.pdf)

참고자료.md파일 404 error 뜹니다. [학술 사이트](http://kangnam.dcollection.net)에서 제목 검색하면 뜹니다.

+ 학술 논문 및 자료 링크 주소가 오류가 나는 경우가 종종 있는 듯 합니다. pdf 업로드 또는 학술 사이트로 하이퍼링크 함이 좋을 듯 합니다.

**Comment by pwjdgus** [comment]
동의합니다.

논문 검색시 팁을 드리자면 구글 스칼라 이용하는 편이 좋습니다.

또한, 최신의 자료를 보는 편이 좋습니다.(인용 횟수도 높으면 좋음)
