### ISSUE TITLE
후보지 선정시 참고사항

### ISSUE THREAD

**Issue by jihoonjeong56** [pwjdgus/Data_Analytics_for_Age_friendly_busan#167]
통계청에서 나온 연령별 총인구 수 및 고령인구비율과 주요 연령 계층별 추계구인에 관한 자료를 찾아봤는데 각 구별로 나눠져있어 도움이 될거 같습니다.
https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1YL20631&conn_path=I2 (고령인구비율)
https://kosis.kr/statHtml/statHtml.do?orgId=202&tblId=DT_0002_2017&conn_path=I2 (주요 연령계층별 추계인구)
https://kosis.kr/statHtml/statHtml.do?orgId=202&tblId=DT_202N_B3&conn_path=I2 (연령별 총인구 현황)

**Comment by pwjdgus** [comment]
감사합니다.

해당 자료를 참고자료에 업로드 가능할까요?
