### ISSUE TITLE
경로당 이용인원에 대한 의견

### ISSUE THREAD

**Issue by HIT18216** [pwjdgus/Data_Analytics_for_Age_friendly_busan#168]
https://www.law.go.kr/LSW//lsBylInfoPLinkR.do?lsiSeq=202054&lsNm=%EB%85%B8%EC%9D%B8%EB%B3%B5%EC%A7%80%EB%B2%95+%EC%8B%9C%ED%96%89%EA%B7%9C%EC%B9%99&bylNo=0007&bylBrNo=00&bylCls=BE&bylEfYd=20180207&bylEfYdYn=Y

경로당 설치규정에 따르면 이용정원 20명이상 이지만 섬 또는 읍·면의 경우 10명이상이라는 예외사항이 있습니다 
적절한 경로당 수를 파악할 때 이용하면 좋을것 같습니다

**Comment by pwjdgus** [comment]
좋습니다. 우선은 생략하고 정리가 된 후에 나중에 적용하는 방법은 어떨까요?

**Comment by HIT18216** [comment]
의견 감사합니다 정리가 된 후 고려해보도록 하겠습니다
