### ISSUE TITLE
경로당 현황에 대한 의견 

### ISSUE THREAD

**Issue by HIT18216** [pwjdgus/Data_Analytics_for_Age_friendly_busan#169]
부산 경로당 내에는 여자만 갈 수 있는 여자경로당과 남자만 갈 수 있는 경로당도 존재합니다.
남자와 여자를 구분하여 추가로 결과를 내는 것은 어떻게 생각하시나요?

**Comment by pwjdgus** [comment]
좋은 아이디어 이지만 우선 큰 틀 먼저 제대로 하는 것이 좋다고 봅니다.

**Comment by HIT18216** [comment]
참고하겠습니다
