### ISSUE TITLE
라벨을 정리해 봤습니다.

### ISSUE THREAD

**Issue by k69121** [pwjdgus/Data_Analytics_for_Age_friendly_busan#170]
의견별, 코드별로 라벨을 정리해봤습니다. 앞으로 라벨을 써주신다면  더욱 원할한 소통이 가능할거같습니다.

**Comment by pwjdgus** [comment]
보기 좋네요

**Comment by pwjdgus** [comment]
기존 라벨 혹시 삭제 가능할까요?

**Comment by OSSnewb** [comment]
라벨을 커스텀 할 수도 있군요

**Comment by paul0817** [comment]
라벨을 정리하니 훨씬 보기 편하네요!

**Comment by k69121** [comment]
기존 라벨은 삭제하고 오류 관련 라벨을 추가하였습니다. 원할한 소통을 위해 써주신다면 감사하겠습니다.
