### ISSUE TITLE
경로당 이용률 관련 질문 

### ISSUE THREAD

**Issue by Syunoh** [pwjdgus/Data_Analytics_for_Age_friendly_busan#172]
각 연령대(65~69, 70~74 등)의 이용률 변화가 크게 나타나서 연령대별로 이용률을 따로 적용하는 것에는 문제가 있을까요?

**Comment by pwjdgus** [comment]
연령대별로 이용률을 어떻게 적용하죠?

**Comment by Syunoh** [comment]
각 연령대별 노인 인구수에 각각 다른 이용률을 적용시키려고 합니다
(예시)
![연령별 이용률 캡쳐](https://user-images.githubusercontent.com/100738448/163566986-7b3bd297-b765-49e0-9080-99420bc55089.png
![부산 노인연령별 인구현황](https://user-images.githubusercontent.com/100738448/163567228-f1926419-43c2-4c72-824d-66d0c22ba845.png)
)

**Comment by k69121** [comment]
다른 이용률을 어떤것으로 적용하실건가요? 그리고 사이트 주소좀 알려주시면 감사하겠습니다.

**Comment by Syunoh** [comment]
간단하게 나타내자면, 65세에서 69세일 경우, 24만 x 이용률(11.2) 그리고 70세에서 74세의 경우, 17만 x  27.7 ~~~ 이런식으로 적용하는 식으로 갈까합니다. 
연령별 인구현황 사이트 - https://jumin.mois.go.kr/ageStatMonth.do
노인 경로당 이용실태 - https://kosis.kr/statHtml/statHtml.do?orgId=117&tblId=DT_117071_042&vw_cd=MT_ZTITLE&list_id=117_11771_003_09&seqNo=&lang_mode=ko&language=kor&obj_var_id=&itm_id=&conn_path=MT_ZTITLE

**Comment by pwjdgus** [comment]
11.2 랑 22.7이라는 값이 어디서 나온거죠?

**Comment by Syunoh** [comment]
정확한 값은 아니겠지만 2020년도 연령대별 경로당 이용률을 임의로 적용했습니다.

**Comment by pwjdgus** [comment]
> 정확한 값은 아니겠지만 2020년도 연령대별 경로당 이용률을 임의로 적용했습니다.

어? 2020년도 경로당 이용률 데이터가 존재 하던가요? 그게 아니면 그냥 임의로 만든 수치?

**Comment by Syunoh** [comment]
kosis에 나와있는 전국단위 데이터라 존재하지만 넓게 적용되기는 힘들 거 같습니다. 위와 같은 예시에선 애매하죠.

**Comment by pwjdgus** [comment]
그렇군요..
