### ISSUE TITLE
오류 관련 라벨을 추가하였습니다.

### ISSUE THREAD

**Issue by k69121** [pwjdgus/Data_Analytics_for_Age_friendly_busan#173]
코드, 데이터 관련 오류 라벨을 추가하였습니다. 그외에 접근성, 이용률등의 이상한 점은 오류가 아닌 하나의 의견으로서 제시해주시면될거같습니다. 추가로 기존에 있던 영어 라벨은 삭제하였습니다.

**Comment by pwjdgus** [comment]
감사합니다
