### ISSUE TITLE
답변 완료된 이슈 관련

### ISSUE THREAD

**Issue by k69121** [pwjdgus/Data_Analytics_for_Age_friendly_busan#175]
답변이 완료되어 해결된 이슈는 closed 기능을 사용하여 따로 분류 하는 것이 깔끔하고 원할 한 소통이 가능할 거 같습니다.  
그렇기에 답변이 완료된 이슈 같은 경우에 closed 기능을 통해 따로 분류하는 것이 어떨까요?

**Comment by pwjdgus** [comment]
closed를 통해 해결되지 못한 issue만 볼 수 있으면 편하겠네요
