### ISSUE TITLE
경로당 위치 의견 - 성별에 따른 경로당 이용률

### ISSUE THREAD

**Issue by kjjyyy** [pwjdgus/Data_Analytics_for_Age_friendly_busan#176]
광주 복지재단에서 실시한 조사에 의하면 남성 노인들은 경로당이나 노인교실보다 노인복지관을 더 선호하는 것으로 나타났다.
경로당은 여성 노인들의 이용률이 상대적으로 더 높은 것으로 나타났다. 

광주지역 노인여가 복지시설 이용자 977명(남자 340명, 여성 637명)을 대상으로 조사한 결과, 
여성 이용률(65.2%)이 남성 이용률(34.8%)보다 2배 가량 높았다. 
남성의 여가시설별 이용률은 노인복지관(46.4%)-노인교실(21.4%)-경로당(11.7%) 순이었다. 
경로당은 여성이용률이 88.3%로 절대 다수를 차지하고 있다.

[https://terms.naver.com/entry.naver?docId=3562295&cid=42107&categoryId=42107 )
https://www.hani.co.kr/arti/area/area_general/817358.html](url)

결론적으로, 성별에 따라 각자 선호하는 노인 복지시설이 다르기 때문에 
경로당의 위치를 정할 때 인근에 사는 노인들의 성별도 고려해 보아야 한다고 생각합니다.

**Comment by pwjdgus** [comment]
비슷한 이슈가 있었습니다. 확인해주세요
