### ISSUE TITLE
경로당 이용률 증가 의견

### ISSUE THREAD

**Issue by 1829122** [pwjdgus/Data_Analytics_for_Age_friendly_busan#178]
2016년 대한노인회가 전국 경로당을 대상으로 실시한 '경로당 활성화 실태조사'를 살펴보면 경로당 프로그램을 만족하지 못하는 이유가
1. 프로그램이 다양하지 못하다(22.8%)
2. 정기적인 프로그램이 제공되지 않고 있다(21.2%)
3. 관심 없는 프로그램이 제공되고 있다(16.5%) 순입니다. 
그래서 제 생각에는 노인분들의 취미, 여가 활동을 조사하고 그 조사 결과를 토대로 프로그램을 재구성 한다면 1, 3의 문제가 해결될거라고 생각하며 그에 따라 이용률이 증가할거라고 생각합니다.     
                                  
P.S. 제가 아직 "재신청합니다"라는 이슈 작성 후에 invite를 받지 못했는데 보내주실 수 있으신가요?

**Comment by pwjdgus** [comment]
비슷한 이슈가 있었습니다 확인바랍니다.

**Comment by 1829122** [comment]
예 알겠습니다.
