### ISSUE TITLE
시각화 관련 추가요소

### ISSUE THREAD

**Issue by as1901as** [pwjdgus/Data_Analytics_for_Age_friendly_busan#179]
현재 경로당 위치 정보를 추가하면 이용자가 기존 경로당과의 거리를 생각해 더 좋은 입지선정을 할 수 있을 것 같습니다.
![image](https://user-images.githubusercontent.com/65982268/163583612-eaa78e87-b3e0-4a64-b962-abfb7f6caa7f.png)

**Comment by pwjdgus** [comment]
입지 제시라서 현재의 경로당 위치는 고려할 필요가 없어 보입니다.

**Comment by as1901as** [comment]
넵 알겠습니다
