### ISSUE TITLE
경로당 입지 관련 의견 - 노인 소득과 관련하여

### ISSUE THREAD

**Issue by kjjyyy** [pwjdgus/Data_Analytics_for_Age_friendly_busan#181]
광주복지재단의 조사에 따르면 노인여가복지시설을 이용하는 노인들은 절반 가까이 
생활비를 ‘국가 연금이나 생활보조금’(45.4%)로 충당했고,  다음이 ‘자녀들이 주는 용돈(28.2%)’이었다. 
[https://www.hani.co.kr/arti/area/area_general/817358.html](url)

국민연금 연구원의 분석에 따르면 노인 부부가 한 달에 필요한 생활비는 최소 210만원이 필요하고 노인 혼자는 130만원이 필요하다는 결과가 나왔다.
은퇴 후 노인가구가 필요한 지출 - 식료품 및 비주류음료(외식비포함) / 주류 및 담배 / 의류 및 신발 / 주택.수도.전기. 및 연료 / 가정용품 및 가사서비스 / 보건 / 교통 / 통신 / 오락 및 문화 / 기타 상품 및 서비스 / 비소비 지출등...
[https://www.ilyosisa.co.kr/news/article.html?no=228767](url)

부산 - 노인기초연금, 독거노인 지원, 어르신 무료급식 지원
가정형편 등으로 식사를 거를 우려가 있는 60세 이상 저소득 노인을 위하여 경로식당 무료급식 지원을 하고있다.
급식기관 82개소 중 복지관의 수가 59개소로 가장 많습니다.  
[https://www.busan.go.kr/depart/welgrand](url)

기사를 통하여 경로당 그 이외의 여러 복지관에서 노인들의 무료급식을 지원하기 때문에
소득이 낮아 의식주에 문제가 생겨 생활을 유지하기 힘든 노인들을위해서라도 기초연금을 받는 노인이 몰려있는 주거지역에 경로당을 더 많이 신설하는 등 경로당 입지조건에 노인의 소득수준을 고려사항으로 넣어보는것도 좋다고 생각합니다.

**Comment by pwjdgus** [comment]
노인 무료 급식소가 존재하는 것으로 알고 있습니다.

이후 노인복지시설 입지 선정을 한다면 고려하는 편이 좋아 보입니다.
