### ISSUE TITLE
입지선정 고려요소에 땅값 추가

### ISSUE THREAD

**Issue by beforemin216** [pwjdgus/Data_Analytics_for_Age_friendly_busan#182]
경로당의 입지를 생각할 때 땅값에 대한 요소도 추가해 보면 어떨까 싶습니다.
접근성이 좋다는 것은 땅값 상승의 요소이기도 합니다.  제한된 예산으로 건설과 운영을 해야 하는 경로당의 특성 상 입지선정에 접근성만 고려한다면 비용 문제가 발생할 수 있기 때문에 땅값도 같이 생각해보면 좋을 것 같습니다.
그리고 접근성 또한 필수이기에 접근성이 제일 좋은 곳을 중심으로 반경을 정하고 그 안에서 땅값을 고려해본다는 것이 제 의견입니다.

[토지이음](https://www.eum.go.kr/web/ar/lu/luLandDet.jsp)에 접속하셔서 원하시는 필지를 열람하시면 평당 개별공시지가를 확인하실 수 있습니다.

**Comment by pwjdgus** [comment]
네 제가 프로젝트 소개하며 요구한 사항입니다.

땅값 즉, 공시지가를 활용한 입지 요소가 필요해 보입니다.

접근성을 고려 후 공시지가를 반영할지, 공시지가 고려 후 접근성을 고려할지는 계속해서 논의를 해보는 것이 좋겠습니다.
