### ISSUE TITLE
입지 분석 모델의 시각화

### ISSUE THREAD

**Issue by TAEYOUNGY00N** [pwjdgus/Data_Analytics_for_Age_friendly_busan#183]
입지 분석 모델에서 부산시 전체의 시각화는 없는것 같습니다. 
예를 들어 이러한 시각화를 추가하는 것도 좋을 것 같습니다.

![부산시 1](https://user-images.githubusercontent.com/100738656/163590757-8ca482b9-819f-46ba-84a5-b972ec60f1a4.png)

![부산시 2](https://user-images.githubusercontent.com/100738656/163590773-b95efc0a-52a9-493c-982f-e59d0594bf64.png)

**Comment by pwjdgus** [comment]
QGIS 사용을 한다면 가능하겠지만

OSMnx는 하드웨어 성능에 의해 조금 힘들어 보입니다.. 우선 가능성은 염두하고 있겠습니다

**Comment by TAEYOUNGY00N** [comment]
네 감사합니다.
