### ISSUE TITLE
수식에 대한 의견 라벨을 추가하였습니다. 

### ISSUE THREAD

**Issue by sammundong** [pwjdgus/Data_Analytics_for_Age_friendly_busan#184]
밑에 아직 closed가 안된 issues를 보면 수식에 대한 의견이고
앞으로 많은 수식에 대한 의견이 있고, 코드를 수정하는데에 있어서 좀 더 편리할거 같아서 추가하였습니다.

**Comment by pwjdgus** [comment]
👍👍
