### ISSUE TITLE
부동산 경제학 이론을 차용한다면 입지 선정에 있어 이론적 근거가 탄탄해질 것 같습니다.

### ISSUE THREAD

**Issue by Sagongmin** [pwjdgus/Data_Analytics_for_Age_friendly_busan#185]
허프의 소매지역이론(확률모형)
허프는 점포의 수익성을 결정하는 것은 소비자의 소비행태로 보고 소비자의 행태를 분석하는 미시적 접근을 통해 다수의 구매중심점이 존재하는 대도시내에서 쇼핑패턴을 결정하는 확률모형을 제시 .
소비자가 특정지역에 쇼핑하러 갈 확률은 거리, 경쟁, 쇼핑센터 수, 쇼핑센터 크기로 결정한다고 가정.
여기서 허프가 말하는 점포를 경로당으로 치환했을 때 경로당 이용률은 거리와 경로당 크기로 결정한다고 가정할 수 있음.
경로당의 유인률은 경로당의 규모에 비례하고 거리의 마찰계수에 반비례.
![스크린샷 2022-04-16 00 29 13](https://user-images.githubusercontent.com/87919031/163590078-f90b54da-8238-42eb-9e4e-d925c5402231.jpg)
다음과 같은 이론으로 어떤 지역(어떤 구)에서 A도시(A 1동, 2동)에서 쇼핑할  확률( 어떤 지역에서 A지역에서 경로당을 이용할 확률)을 구할 수 있음. 단, 공간마찰계수가 2이라고 가정.
* 공간마찰계수 : 고객이 특정 점포를 이용하는데 따른 교통조건이나 하천 등의 방해요소를 말한다. 즉 시장의 교통조건과 쇼핑물건의 특성에 따라 조건이 악화되면 공간마찰계수는 커짐.  
예를 들어 
1. A도시의 매장면적 1000m^2 , A도시까지의 거리 10km 
2. B도시의 매장면적 250m^2, B도시까지의 거리 5km 
3. C도시의 매장면적 180m^2, C도시까지의 거리 3km
A 도시의 유인력 =  1000/10^2        -> ^2(공간마찰계수)
B 도시의 유인력 = 250/5^2
C도시의 유인력 = 180/ 3^2
*A도시로 쇼핑 갈 확률 (시장점유율)(A도시 경로당을 이용 할 확률 =  A도시의 유인력 / A + B + C 도시의 유인력 = 10 / 10 + 10 + 20 = 10 / 40 = 0.25
*만약 어떤지역(어떤 구)의 인구가 10만명이라면 A도시 경로당을 이용 할 인구는 10만명 * 0.25 = 25,000명이 됨. 
도출된 예상 이용 인구를 이용해서 크리스탈러가 말하는 배후지 완결형의 모습으로 경로당 입지를 선정할 수 있을 듯 함.
![스크린샷 2022-04-16 00 52 35](https://user-images.githubusercontent.com/87919031/163592384-19fb9a4c-19f5-42d3-902e-5741b9a5732b.jpg)
! 배후지 외접형 : 중심지의 서비스를 제공받지 못하는 지역이 발생한다. 
! 배후지 중첩형 : 중심지 간의 지나친 경쟁으로 불필요하게 중복되는 지역이 발생한다.
O 배후지 완결형 : 겹치거나 소외되는 지역이 존재하지 않고 재화나 서비스를 제공한다.

**Comment by pwjdgus** [comment]
이론에 대해 이해할 시간이 필요해 보이네요

**Comment by pwjdgus** [comment]
경로당은 소비자라는 개념이 없는 시설이라 생각하는데 허프 이론이 과연 적용 가능할지 의문입니다.
