### ISSUE TITLE
독거노인 관련 의견

### ISSUE THREAD

**Issue by 1829122** [pwjdgus/Data_Analytics_for_Age_friendly_busan#186]
https://www.index.go.kr/unify/idx-info.do?idxCd=8039
여기를 보시면 독거노인의 수는 증가하고 있습니다.

https://kosis.kr/statHtml/statHtml.do?orgId=117&tblId=DT_117071_042&vw_cd=MT_ZTITLE&list_id=117_11771_003_09&seqNo=&lang_mode=ko&language=kor&obj_var_id=&itm_id=&conn_path=MT_ZTITLE
노인의 경로당 이용 실태조사입니다. 경로당 전체 이용률은 28.1%인 반면에 독거노인은 39%가 경로당을 활용하고 있습니다.

https://kosis.kr/statHtml/statHtml.do?orgId=143&tblId=DT_11430264_2017&vw_cd=MT_ZTITLE&list_id=114_11437_007_17&seqNo=&lang_mode=ko&language=kor&obj_var_id=&itm_id=&conn_path=MT_ZTITLE
경로당 이용 목적입니다. 이용 목적은 마을 주민과의 유대, 친교가 72%로 제일 높습니다.

https://data.busan.go.kr/dataSet/detail.nm?publicdatapk=15026028&contentId=10
부산시 북구 독거노인 현황입니다. 공공데이터포털 다른 구의 현황도 있지만, 개별로 올려져 있어서 북구만 일단 올리겠습니다.

따라서, 경로당 이용 목적에서 72%인 마을 주민과의 유대, 친교와 밀접한 연관이 있다고 생각하는 독거노인의 비율도 입지 조건에 포함되면 좋다고 생각합니다

**Comment by pwjdgus** [comment]
사회적 참여 요소를 고려한 좋은 아이디어 같습니다.

다른 요소로 경로당 이용률을 높여도 많은 노인(독거 노인 포함)이 경로당을 찾을 것이라 생각합니다.
