### ISSUE TITLE
경로당 이용에 관련한 기타 제언

### ISSUE THREAD

**Issue by hesuhesu** [pwjdgus/Data_Analytics_for_Age_friendly_busan#190]
[논문 참조](http://koreascience.or.kr/article/JAKO201711656577327.pdf) // 링크 오류 없습니다.

경로당의 필요성과 코드 리뷰, 자료 제시 등 많은 분들이 좋은 기여를 해주시는 것 같습니다.
추가로 한 가지 의견이 있다면 경로당을 이용해서 얻을 이점, 긍정적 이유가 있다면 좋을 듯 합니다.
시설을 공급하고 처우 개선을 해도 이용자가 없으면 무용지물이기 때문입니다.
최종적으로 사회 활동 및 여가 활동의 장점을 부각하면 경로당을 이용할 목적과 홍보에 도움이 된다고 생각합니다.

**Comment by pwjdgus** [comment]
음.. 제 생각으로는  프로젝트 주제와는 다소 거리 있어보입니다.

저희는 ~~~요소를 반영하여 적합한 입지를 제시했다 는 주장을 하고
제시하신 내용은 공무원들 or 경로당 시설 관련자들이 하는게 맞다고 생각하는데 어떤가요?

**Comment by hesuhesu** [comment]
경로당 활성에 초점을 두니 본질을 벗어난 이질적인 얘기를 한 거 같습니다..
동의합니다. 더 고도화된 근거를 둔 프로젝트가 우선인 듯 합니다.
