### ISSUE TITLE
경로당 이용률에 대한 의견

### ISSUE THREAD

**Issue by Kim-qjaJ** [pwjdgus/Data_Analytics_for_Age_friendly_busan#191]
현재 경로당은 나이에 의해 차별과 왕따가 생기는 경우가 있는데 노인 중에서도 젊은 층의 노인들이 이러한 현상 때문에 경로당에 적응하기 힘들어 경로당의 이용률이 떨어진다고 생각이 듭니다.
 그리고 이렇게 적응 못한 노인들이 시간이 지나고 그 밑의 노인들에게 차별과 왕따를 하는 악순환이 일어나는데 경로당을 만들 때 나이대별로 나누면 경로당 이용률이 늘어날 것으로 보입니다. 
 나이대별로 세분화를 시키며 여러 건물을 짓지 못한다면 크게 건물을 지을 곳을 찾고 복지관 형식으로 짓고 세분화를 하는 것도 좋다고 생각합니다.

**Comment by pwjdgus** [comment]
마찬가지로 주제와 벗어난 의견 제시라고 생각합니다.

현재 경로당 운영에 관련된 내용을 제시했다 생각합니다.

혹시 다른 의견 있으시면 이야기 해주세요!
