### ISSUE TITLE
입지 관련 의견 - 경로당 이용자의 인지성

### ISSUE THREAD

**Issue by paul0817** [pwjdgus/Data_Analytics_for_Age_friendly_busan#192]
**인지성**은 시설을 찾아가는데 필요한 요소로서 시각 및 공간 지각 능력이 떨어지는 노인 이용자를 위해 중요하다고 생각합니다.

인지성이 뛰어난 곳으로는 공공시설인접, 주거지인접, 근린공원인접 등이 있습니다.

따라서  입지 조건에 인지성을 반영한다면  더욱 최적의 입지를 선정할 수 있다고 생각합니다.

**Comment by paul0817** [comment]
https://dcollection.kongju.ac.kr/public_resource/pdf/000000028000_20220416015020.pdf 관련 논문입니다.

**Comment by pwjdgus** [comment]
접근성 고려시에 주거지 인접, 공공시설 인접에 대한 이슈가 있었습니다.
잘 엮어보면 될 듯 합니다

**Comment by paul0817** [comment]
확인하겠습니다

**Comment by paul0817** [comment]
추가적으로 주거지인접형은 주거지 내에 위치하고 있어 인지성이 떨어지나 이용자들이 대부분 근린주구에 거주하고 있어 큰 문제가 되지 않습니다. 그러나 인접도로가 좁아서 교통이 혼잡하고 주차공간 확보가 어려우며 외부공간 확보가 어려워 야외활동에 제한이 있습니다.
근린공원인접형은 주거지인접형과 주변환경이 비슷하지만 근린공원이 인접하고 있어 충분한 외부공간과 야외 운동기구가 설치되어 있어서 야외활동과 야외 프로그램 운영이 용이합니다. 
공공시설인접형은 주변환경은 주거지인접형과 비슷한 조건을 가지고 있으나 주거지인접형에 비해 혼잡하지 않고 시각적 개방감을 확보하고 있습니다.
