### ISSUE TITLE
다른 지역과의 경로당 이용률 비교

### ISSUE THREAD

**Issue by MwaungMwaung** [pwjdgus/Data_Analytics_for_Age_friendly_busan#193]
[2020년도_노인실태조사_보고서.pdf](https://github.com/pwjdgus/Data_Analytics_for_Age_friendly_busan/blob/main/%EC%B0%B8%EA%B3%A0%EC%9E%90%EB%A3%8C/2020%EB%85%84%EB%8F%84_%EB%85%B8%EC%9D%B8%EC%8B%A4%ED%83%9C%EC%A1%B0%EC%82%AC_%EB%B3%B4%EA%B3%A0%EC%84%9C.pdf)에서 가져온 아래의 표를 보면 부산은 경로당 이용률이 가장 낮으며 이용률이 가장 높은 전남과 비교했을 때 40.3%의 큰 차이를 보입니다.
![arearate](https://user-images.githubusercontent.com/72175635/163595067-61a2d481-ced9-40b2-b9c7-02ed545a695a.png)

대한민국 통계청 [지역별 면적](https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1ZGA17&conn_p-ath=I2)에 따르면,
전남 면적은 12,348km^2, [경로당 수](https://www.jeonnam.go.kr/contentsView.do?menuId=welfare0502040000)는 9,047개이므로 **1km^2 당 1.36개**의 경로당이 있습니다.
부산 면적은 770km^2, 경로당 수는 2,341개이므로 **1km^2 당 3.04개**의 경로당이 있습니다.

면적 대비 경로당 수만 놓고 보면 부산이 전남의 두 배 이상 많습니다. 그럼에도 불구하고 이용률에서 이토록 뒤처지는 이유를 알아낸다면 경로당 이용률 원인 분석에 도움이 될 것입니다. 

또한 이처럼 부산과 다른 지역의 차이를 비교해보는 데이터나 자료가 더 필요한 것 같습니다.

**Comment by pwjdgus** [comment]
👍

**Comment by k69121** [comment]
정말 좋은거같습니다. 부산이 경로당 이용률 최하위인지는 몰랐네요.

**Comment by gymdong** [comment]
향후 이용 희망률도 가장 낮은 것을 보면 확실히 부산만의 문제가 있는 것 같습니다.

**Comment by leeseungmin-kr** [comment]
자료 조사 시점이 코로나시국인 2020년도인 점과 표본이 낮은 점을 봤을때 좋은 자료라고 보기에는 어려울거 같습니다.

**Comment by KoEunseong** [comment]
타지역과 비교자료가 경로당 이용률 파악에 도움이 될만한 요소인것 같습니다. 추가적으로 관련 조사를 할만한 주제인것 같아요!

**Comment by SIMOOLOOK** [comment]
도시지역과 비도시지역의 환경적 차이를 지역 간 경로당 이용률 차이의 원인으로 제시합니다. 

도시지역은 경로당 외에도 복지센터, 노인교실, 종교시설 등 대체시설이 많습니다. 
따라서 순수하게 경로당 이용률만을 조사했을 때 도시지역은 비도시지역에 비해 상대적으로
낮은 이용률이 나온 것 같습니다.

위의 표에서 서울, 부산, 인천, 울산 등의 도시지역이 주를 이루는 지역의 이용률은 10%대인 반면,
전남, 경북, 충북 등 비도시지역을 많이 포함하는 지역의 이용률은 40%대임을 볼 수 있습니다. 

참고자료
[전라남도 행정구역](https://www.jeonnam.go.kr/contentsView.do?menuId=jeonnam0602030000)
[부산광역시 행정구역](http://busan.grandculture.net/Contents?local=busan&dataType=01&contents_id=GC04209602)
[비수도권 중소도시의 경로당 이용권에 관한 연구 - 충주시 도시지역과 비도시지역을 중심으로.pdf](https://github.com/pwjdgus/Data_Analytics_for_Age_friendly_busan/files/8499601/-.pdf)
