### ISSUE TITLE
시장 내 경로당 입지

### ISSUE THREAD

**Issue by beforemin216** [pwjdgus/Data_Analytics_for_Age_friendly_busan#195]
시장은 많은 사람들이 모이고 그중에서 노인이 많습니다
2017년 [수원시의 전통시장 이용 통계](https://kosis.kr/statHtml/statHtml.do?orgId=611&tblId=DT_611003_2017040&conn_path=I2)에는 60세 이상의 전통시장 이용률이 57.6%로 15~59세의 33.2%보다 약 두 배 많습니다.
부산은 부전시장, 자유시장, 깡통시장 등 172개의 전통시장이 곳곳에 있고, 이 시장들 안에 경로당의 입지를 고려해 본다면 이용률 면에서도 좋을 것 같습니다.

**Comment by leeseungmin-kr** [comment]
이용율도 좋지만, 인구수와 거리를 따져서 많은 이들이 이용할 수 있는것이 더 좋지 않을까요?
그리고 시장이 없는 곳에 많은 노인들이 사는 경우에는 오류를 범할수도 있다고 생각합니다.

**Comment by paul0817** [comment]
저도 @leeseungmin-kr님과 같은 생각입니다.
