### ISSUE TITLE
교통이 발달된 입지 고려

### ISSUE THREAD

**Issue by rvjst** [pwjdgus/Data_Analytics_for_Age_friendly_busan#197]
입지 조건에 교통을 추가하는 것이 좋을 것 같습니다.
걸어서 10분이 걸리는 경로당을 예측하여 짓는다 하더라도 다 만족을 시키기에는 큰 어려움이 있을 것입니다. 
또 각 경로당 사이의 차이로 인해 좀 더 먼 경로당을 가고 싶어하는 경우도 존재 할 수도 있습니다.
교통이 발달된 곳에 입지를 선정하게 되면 위의 문제점 해결이 될 뿐만 아니라
오히려 참여가 저조한 경로당도 행사나 이벤트 등을 통해 접근성을 높힐 수 있다고 생각합니다.

[부산광역시 정류소 검색](https://gist.github.com/ihoneymon/652be052a0727ad59601)에서 정류소 위치를 확인 하실 수 있습니다.

**Comment by pwjdgus** [comment]
> 입지 조건에 교통을 추가하는 것이 좋을 것 같습니다. 걸어서 10분이 걸리는 경로당을 예측하여 짓는다 하더라도 다 만족을 시키기에는 큰 어려움이 있을 것입니다. 또 각 경로당 사이의 차이로 인해 좀 더 먼 경로당을 가고 싶어하는 경우도 존재 할 수도 있습니다. 교통이 발달된 곳에 입지를 선정하게 되면 위의 문제점 해결이 될 뿐만 아니라 오히려 참여가 저조한 경로당도 행사나 이벤트 등을 통해 접근성을 높힐 수 있다고 생각합니다.
> 
> [부산광역시 정류소 검색](https://gist.github.com/ihoneymon/652be052a0727ad59601)에서 정류소 위치를 확인 하실 수 있습니다.

경로당 특징 차이로 인해 다른 경로당을 가고 싶어하는 노인이 다수인지 알아야 할 것 같습니다.
제 생각은 뭐든 모두를 만족 시키기엔 답이 없다고 생각합니다 

만약, 교통이 발달된 곳에 입지를 선정할 경우 교통이 발달된 지역이라는 기준도 애매하다 생각합니다.
