### ISSUE TITLE
경로당 입지 주변 시설 고려

### ISSUE THREAD

**Issue by gymdong** [pwjdgus/Data_Analytics_for_Age_friendly_busan#198]
2020년 실시된 노인실태조사 결과에 따르면 도보가 20분 정도까진 걸리더라도 대체적으로 만족하는 모습을 보였습니다.
그렇다면 신설될 경로당 입지에 대해서 고려할 때 도보를 20분 정도까지 고려하는 대신 조금 더 걸리더라도 주변 편의시설 등에 대해서도 고려하는 것은 어떨까요?
실제 이용하는 노인들 입장에서도 주변에 편의시설이 존재한다면 도움이 될 것이고, 운영자 입장에서도 다양한 콘텐츠 창출의 기반이 될 수 있을 것 같습니다.

예를 들면 산출된 최적 입지들에 대해서 주변에 편의시설이 존재한다면 가중치를 주는 방식이나, 
(구체적으로 어떻게 편의시설의 존재를 인식하게 할 지 생각해야함)
산출된 최적 입지들의 좌표를 지도 api를 사용해 마킹하여 우리가 편하게 볼 수 있는 지도 형태에서 볼 수 있도록 하는 것입니다.
(시각화 된 입지의 좌표만 있다면 바로 가능)

전자의 경우 바로 시각화된 데이터를 볼 수 있어서 편할 것 같고,
후자의 경우 직접 그 주변을 다 살펴보며 입지를 고려할 수 있을 것이고 실제로 설치를 고려할 때 그 주변에 대해 잘 아는 사람이 있다면 도움이 될 수도 있을 것이라고 생각합니다.

**Comment by pwjdgus** [comment]
음 부산의 경우 평지가 많이 없어 실제 노인들의 경우 먼 거리를 선호하지 않습니다. (설문조사 결과)

주변에 편의 시설이 있다면 가중치를 주는 방법은 좋으나 고민이 많이 필요해 보입니다.

**Comment by gymdong** [comment]
혹시 설문조사 결과를 어디서 볼 수 있을지 알 수 있을까요?

**Comment by pwjdgus** [comment]
발표자료요

**Comment by pwjdgus** [comment]
ppt에 있었던 걸로압니다

**Comment by gymdong** [comment]
그럼 산출된 지역을 지도 api를 통해 지도에서 보여주는 것은 어떻게 생각하시나요?

**Comment by pwjdgus** [comment]
지도 api가 없어도 위경도 값을 알면 라이브러리로 가능합니다.

* folium 라이브러리

**Comment by gymdong** [comment]
그렇군요! 감사합니다 그렇다면 folium 라이브러리 사용에 대해선 어떻게 생각하시나요? 괜찮은 의견 같다면 사용해보려고 하는데..

**Comment by pwjdgus** [comment]
상관은 없습니다. 

주변 시설 고려한다면 그래프가 필연적으로 사용될 거라 task가 많아질 수 있어요.

osmnx는 그래프를 지원하고 있어 편리합니다.

또한, 두가지의 라이브러리를 혼합해서 사용해도 괜찮겠지만 오버헤드가 클 것 같아요
