### ISSUE TITLE
최적입지에 고도를 고려 한다면

### ISSUE THREAD

**Issue by hhhhmang** [pwjdgus/Data_Analytics_for_Age_friendly_busan#200]
Open Route Service를 이용하면 경로의 도로 포장상태, 도로 종류, 경사도를 그래프로 분석이 가능한데
어떻게 생각하시나요 ?

**Comment by leeseungmin-kr** [comment]
궁금해서 사이트 들어가서 사용해보니 
한국에 대한 고도는 아직 지원하지 않습니다. 미국,  유럽은 가능하네요!

**Comment by pwjdgus** [comment]
osmnx로 고도(경사) 시각화 가능합니다.
