### ISSUE TITLE
공원, 산책로 등의 요소 고려

### ISSUE THREAD

**Issue by 1829122** [pwjdgus/Data_Analytics_for_Age_friendly_busan#201]
노인분들의 여가 활동 중 가장 많은 비율을 차지하는것은 휴식활동이 52.7%로 가장 많았으며, 52.7%중  34.1%가 산책입니다.
많은 노인분들이 산책을 즐기시는 만큼 입지 분석을 할 때 공원, 산책로 등을 추가해서 입지 분석을 한다면 보다 좋은 입지가 나온다고 생각합니다.

**Comment by pwjdgus** [comment]
입지 대해서 다양한 시설을 고려하자는 의견이 많았습니다. 이런 의견을 모아서 논의 하는 것은 어떨까요 

예를 들어 Milestone을 통해 하나로 통합하거나 이슈 Label을 통해 분류하는 방법입니다.

**Comment by 1829122** [comment]
좋은 생각인거 같습니다.
