### ISSUE TITLE
경로당 최적 입지 관련 의견

### ISSUE THREAD

**Issue by 02chan** [pwjdgus/Data_Analytics_for_Age_friendly_busan#203]
PPT 파일에서 노인의 이동수단과 시간을 고려했을 때 걸어서 10분 이내의 위치가 최적 입지라고 선정하셨습니다. 
노인들 기준 걸어서 10분 이내의 위치가 몇 km이내인지 명확하게 적혀 있으면 좋을 것 같습니다.
ex) 걸어서 10분 이내의 위치 (약 n km 이내)

**Comment by pwjdgus** [comment]
글쎄요 노인들이 걸어서 10분 이내 위치가 몇 km일까요...?

**Comment by 02chan** [comment]
정확한 거리가 표현되면 좋겠다고 생각을 하였습니다.. 아무래도 노인분들 걸어서 10분 이내 위치면 m단위가 맞겠네요... 생각이 좀 짧았던거 같습니다.

**Comment by pwjdgus** [comment]
> 정확한 거리가 표현되면 좋겠다고 생각을 하였습니다.. 아무래도 노인분들 걸어서 10분 이내 위치면 m단위가 맞겠네요... 생각이 좀 짧았던거 같습니다.

아닙니다 다만 거리 정도(m. km)
