### ISSUE TITLE
경로당 주별 이용 횟수

### ISSUE THREAD

**Issue by 1829122** [pwjdgus/Data_Analytics_for_Age_friendly_busan#204]
https://kosis.kr/statHtml/statHtml.do?orgId=143&tblId=DT_11430262_2017&vw_cd=MT_ZTITLE&list_id=114_11437_007_17&seqNo=&lang_mode=ko&language=kor&obj_var_id=&itm_id=&conn_path=MT_ZTITLE
경로당 주별 이용 횟수입니다. 
주별 이용 횟수를 알면 경로당에서 운영하는 프로그램 등을 짤 때 기간에 맞춰 보다 효율적으로 프로그램을 짤 수 있고 결론적으로 만족도가 오를거라고 생각합니다.

**Comment by pwjdgus** [comment]
>주별 이용 횟수를 알면 경로당에서 운영하는 프로그램 등을 짤 때 기간에 맞춰 보다 효율적으로 프로그램을 짤 수 있고 결론적으로 만족도가 오를거라고 생각합니다.

저희가 프로그램을 짜지는 않습니다
