### ISSUE TITLE
입지 선정에 대한 의견

### ISSUE THREAD

**Issue by HIT18216** [pwjdgus/Data_Analytics_for_Age_friendly_busan#205]
10분 이내의 걸어서 경로당 접근이 92.8퍼센트로 가장 높긴 하지만
![화면 캡처 2022-04-16 151347](https://user-images.githubusercontent.com/100738514/163664300-1452ed6f-6ba7-4283-956d-582d5c55b38f.png)
버스정류장 정도는 입지선정할때 고려사항이 되는 것은 어떨까 의견 제시합니다.
노인들이 주로 이용하는 대중교통이므로 병원,산책로와 함께 고려해볼만 한 사항이라고 생각합니다

**Comment by pwjdgus** [comment]
어떤식으로 고려하는게 좋을까요

**Comment by HIT18216** [comment]
모든 것을 충족 시키기는 어렵다고 생각합니다 그러므로  버스 정류장과 병원, 산책로 등을 노인에게 필요한 우선순위를 매겨 주변을 원으로 겹쳐서 교집합되는 곳들의 우선순위가 높은 곳이  경로당 입지 선정시 가장 좋은 곳일 것 같습니다 


추가로 읍,면 등 교통이 잘 발달되지 않은 곳은 고려 사항에서 빼는 것이 좋겠지만 
대부분의 부산의 도시의 경우 교통이 잘 발달되어 있으니 버스 정류장과 가까운 경로당이 위치하면 부산의 높은 고도의 문제도 
어느 정도 해결 가능 하다고 생각합니다

**Comment by pwjdgus** [comment]
교통이 잘 발달된 것의 기준이 모호하지 않나요? 사람마다 다른 객관적 지표라고 생각합니다.

원으로 겹쳐서 교집합 되는 곳들의 아이디어는 좋습니다. 이것을 그래프 적으로 생각하면 어떨까요?
왜냐면 저희가 사용할 GIS 도구는 그래프 기반의 OSMnx입니다.

**Comment by HIT18216** [comment]
의견 감사합니다 교통이 잘 발달된 것의 기준은 다시 한번 생각해보겠습니다
