### ISSUE TITLE
경로당 접근성및 이용률에 관한 의견

### ISSUE THREAD

**Issue by Kim-qjaJ** [pwjdgus/Data_Analytics_for_Age_friendly_busan#206]
경로당이 노인들에게 있어 휴식과 여가의 공간이 되는 모습이 아니면 추후 노인들의 경로당 이용률을 낮출 수 있다 생각합니다.
https://m.blog.naver.com/PostView.naver?isHttpsRedirect=true&blogId=gimpo2010&logNo=221970189046
http://www.kgmaeil.net/news/articleView.html?idxno=286084
위의 블로그와 기사는 노인들은 무릎과 관절이 많이 약해지기 때문에 바닥에 주로 앉아 시간을 보내는 좌식 형태의 경로당에 의자와 식탁을 지원해준다는 내용입니다.
해당 블로그와 기사 같이 경로당 내부의 구조를 개선하는 방안을 찾는다면 경로당의 이용률이 증가하고 접근성을 높일 수 있을 것이라 생각합니다.

**Comment by pwjdgus** [comment]
내부 구조에 관한 내용은 주제와 다소 거리가 있어보입니다..
