### ISSUE TITLE
경로당 이용자 연령 관련

### ISSUE THREAD

**Issue by 02chan** [pwjdgus/Data_Analytics_for_Age_friendly_busan#207]
![캡처](https://user-images.githubusercontent.com/86522084/163664767-79b29f9c-ba1d-47d1-a04c-27f55ea79ff9.PNG)

위 자료와 같이 경로당은 80세 이상 노인들이 절반 이상을 차지합니다.
고령자 분들이 많기 때문에 응급 상황등을 대비하여서 병원 위치 또한 고려해 보는게 어떤지 의견 내봅니다.

[자료 출처](http://lps3.www.dbpia.co.kr.libproxy.donga.ac.kr/pdf/pdfView.do?nodeId=NODE07273703).

**Comment by pwjdgus** [comment]
네 경로당 주변 시설에 대한 의견은 많이 있었습니다.

한번 읽어보시고 종합해보면 좋을 것 같아요!
