### ISSUE TITLE
경로당 위치에 관하여

### ISSUE THREAD

**Issue by 02chan** [pwjdgus/Data_Analytics_for_Age_friendly_busan#209]
![unknown](https://user-images.githubusercontent.com/86522084/163665205-5a805f1d-44fa-4278-9911-d600cb8e3e2c.jpeg)

위 자료를 보면, 인천광역시 남동구 구월3동의 경로당은 경로당이 조금 높은 곳에 위치해 있어서 침수와 같은 재해애 안전하다고 합니다. 또한 도보 5분 이내의 거리에 임시주거시설과 대피소 등이 있음을 알 수 있습니다. 이를 참고하는게 좋다고 생각을 합니다.

[자료 출처](http://lps3.www.dbpia.co.kr.libproxy.donga.ac.kr/pdf/pdfView.do?nodeId=NODE07588286)

+) 다른 좋은 의견들도 종합하여 보겠습니다!

**Comment by pwjdgus** [comment]
약간 딜레마가 있네요 높은 곳에 위치하면 노인들이 힘들 것이지만 침수 피해는 비교적 안전하고..
