### ISSUE TITLE
읍·면 지역과 동 지역의 이용률과 향후 이용희망률 비교

### ISSUE THREAD

**Issue by HIT18216** [pwjdgus/Data_Analytics_for_Age_friendly_busan#211]
![화면 캡처 2022-04-16 151347](https://user-images.githubusercontent.com/100738514/163666503-175dbb33-be6d-45dd-8dd9-619ea7238e4f.png)

읍·면 지역의 이용률과 향후 이용희망률이 동 지역에 비교하여 약 2배정도 차이가 납니다 
두 지역의 차이점을 비교하는 것도 동 지역의 이용률을 올리는데 도움이 될까요?

**Comment by pwjdgus** [comment]
음 도움이 될지 아닐지 모르겠지만 의미 있는 비교라고 생각합니다.

**Comment by SIMOOLOOK** [comment]
issue #193 의 내용과 겹치는 것 같습니다.

**Comment by SIMOOLOOK** [comment]
#193 과 연관되는 내용 같습니다. 참고하시면 좋을 것 같아요.
