### ISSUE TITLE
논문, 자료를 참고한 이슈에서 링크나 출처를 공개하면 좋을 거 같습니다.

### ISSUE THREAD

**Issue by hesuhesu** [pwjdgus/Data_Analytics_for_Age_friendly_busan#213]
많은 분들이 이슈에 참여해주시는데, 자료에 출처가 없으면 차후에 remind하기 힘들 것 같습니다(특히 수치적 부분은 기억하기 힘듬)

사진만 캡쳐해서 올리거나 자료의 일부만 기입하는 방식 보다는 **링크나 출처, 자료 파일을 첨부**하면 좋을 거 같습니다.

이는 중복된 자료, 의견에 낭비하는 시간 억제 및 새로운 자료 탐색에 신속성을 더할거라 생각합니다.

모니터링 하시는 분들께서 중복된 내용은 잡아주고 계시지만, 더 많은 자료가 발생한다면 힘들어질 것 같습니다.

+ 출처, 링크, 자료파일 꼭 첨부해주시면 좋을 듯 합니다!

**Comment by paul0817** [comment]
동의합니다.
