### ISSUE TITLE
문서 관련 의견 

### ISSUE THREAD

**Issue by Sagongmin** [pwjdgus/Data_Analytics_for_Age_friendly_busan#214]
오픈소스 프로젝트의 강점은 전 세계 개발자들의 다양한 의견을 적극적으로 수용할 수 있다는 점이라고 생각합니다. 프로젝트가 고도화 될 수록 다양한 관점에서 바라본 의견이 필요할 것이고 따라서 세계 공용어인 영어가 필요해 보입니다. 따라서 기존의 한글 문서를 외부인이 읽기 좋게 요약/개선하고 영어 버전 번역 문서를 만드려고 하는데 어떠신가요? * 국내 1만 K이상 받은 토스트 ui 에디터, 파이어폭스 프로톤 디자인 UI/UX개선 프로젝트등이 영어를 기본으로 프로젝트를 운영하고 있었습니다.

**Comment by pwjdgus** [comment]
그 부분은 프로젝트 개발이 완료되고 문서 작업을 하는 편이 더 좋지 않을까요?

정리된 문서화가 가능하지 않을까 생각합니다
