### ISSUE TITLE
부산 광역시 연령별 경로당 현황 관련 자료

### ISSUE THREAD

**Issue by KoEunseong** [pwjdgus/Data_Analytics_for_Age_friendly_busan#215]
![image](https://user-images.githubusercontent.com/98599867/163671029-78fc281b-5a0d-4c4e-acfd-e5b015271b27.png)
위에 데이터를 바탕으로 실질적인 부산광역시에서 경로당 등록인원은 71 ~ 80세의 노인들이 가장 많은 비율을 차지하는 것을 알 수 있습니다. 따라서 경로당 프로그램을 구성할 때  71~80세의 고령, 거동불편 어르신들의 특성에 부합하는 프로그램의 개발과 지원이 필요할거 같습니다.

참조: 고령화 대책의 효율적 추진을 위한 거점경로당 육성방안 : 부산광역시 경로당 실태 분석을 중심으로 / A Study on the Establishment of Main Senior Citizen Centers for the Effective Implementation of Aging-related Policies : Focusing on the operational status of senior citizen centers in Busan

**Comment by paul0817** [comment]
#204 와 비슷한 답변일 것 같네요.

**Comment by pwjdgus** [comment]
말했지만 경로당에서 시행하는 프로그램은 저희가 할 것이 아니라 생각합니다. 입지 제시에 관점을 둬야합니다
