### ISSUE TITLE
경로당 입지 관련 의견제시

### ISSUE THREAD

**Issue by Kim-qjaJ** [pwjdgus/Data_Analytics_for_Age_friendly_busan#217]
주택가보다 좁은 공간에 거주민들이 많은 아파트 같은 경우 osmnx에 도보 기준 값이 크게 나올 것인데 이를 통해 아파트 단지인지 아닌지 판단 후 아파트 단지 내 경로당 설치를 고려하는 것도 나쁘지 않다고 생각합니다.

**Comment by pwjdgus** [comment]
대부분의 아파트는 경로당을  포함하고 있다고 합니다 !
