### ISSUE TITLE
issue 간 내용 중복에 관하여

### ISSUE THREAD

**Issue by SIMOOLOOK** [pwjdgus/Data_Analytics_for_Age_friendly_busan#218]
비슷한 내용의 이슈가 지속적으로 올라옵니다.

현재는 @pwjdgus 님이 중복되는 내용에 대해 관리를 하고 있는 상황이지만,
지금처럼 이슈가 올라온다면 앞으로 프로젝트가 진행되면서 이슈는 쌓이고 관리는 힘들어질 것으로 예상합니다.

프로젝트가 더 진행되기 전에 아래의 문화가 자리 잡았으면 좋겠습니다. 

- 의견을 쓰기 전에 해당되는 라벨을 눌러 **앞서 관련된 내용의 이슈가 없었는지 확인**합시다.

- 만약 내용이 비슷한 부분이 있더라도 올려야 하는 경우엔 **이슈를 태그**합시다. (태그 방법은 **#이슈번호** 입니다.)

- 본인이 아니더라도 관련 내용이 있다면 댓글로 태그를 달아주면 좋을 것 같습니다. 

추가할 내용이 있다면 의견 달아주시면 감사하겠습니다.

**Comment by pwjdgus** [comment]
너무 동의합니다

**Comment by SIMOOLOOK** [comment]
#213 에서 언급된 것처럼 참고자료에 대한 링크나 pdf 파일 첨부도 하나의 문화로 자리 잡으면 좋을 것 같습니다
