### ISSUE TITLE
연령별 경로당 이용률 고려

### ISSUE THREAD

**Issue by Quwhsa** [pwjdgus/Data_Analytics_for_Age_friendly_busan#219]
https://kosis.kr/statHtml/statHtml.do?orgId=117&tblId=DT_117071_042&vw_cd=MT_ZTITLE&list_id=117_11771_003_09&seqNo=&lang_mode=ko&language=kor&obj_var_id=&itm_id=&conn_path=MT_ZTITLE
이 자료를 보시면 65세~69세 노인들의 경로당 이용률은 11%정도인 것에 반해 85세 이상의 노인들의 경로당 이용률은 47%에 달합니다.
그러므로, 노인 평균 연령이 높은 곳에 경로당을 설치 한다면 더 높은 이용률을 얻을 수 있을 것이라고 생각합니다.

P.S 죄송합니다. 제가 invite 받는 것을 잊어버려서 그런데 한번 더 보내주실 수 있을까요?

**Comment by pwjdgus** [comment]
비슷한 이슈 참고해주세요.
그리고 이슈 등록시 Labels 추가 부탁합니다.
