### ISSUE TITLE
참고자료-참고자료.md 문제

### ISSUE THREAD

**Issue by kjjyyy** [pwjdgus/Data_Analytics_for_Age_friendly_busan#222]
참고자료.md의  <경로당 서비스 질에 따른 만족도> 링크를 타고 들어가면 요청한 페이지를 찾을 수 없다고 뜹니다 .. 저만 그런가요.. 아니라면 수정부탁드립니다.

**Comment by dainnnnn** [comment]
저도 그렇게 나오네요
