### ISSUE TITLE
시각화 관련 의견

### ISSUE THREAD

**Issue by dainnnnn** [pwjdgus/Data_Analytics_for_Age_friendly_busan#223]
시각화 관련하여 국토정보지리원 - [국토정보플랫폼](http://map.ngii.go.kr/mn/mainPage.do) 을 참고하는 것은 어떤가요??
다양한 지도 자료와 시각화 정보를 제공하는 쉽고 편리한 대국민 개방 서비스로 국토정보맵을 통해 수치지도, 항공사진, 정사영상 등 다양한 지도 다운 가능이 가능하여 시각화 자료를 보충하는데 도움이 될 것 같습니다.

**Comment by pwjdgus** [comment]
그렇군요
