### ISSUE TITLE
경로당 입지선정시 체육시설 고려

### ISSUE THREAD

**Issue by KoEunseong** [pwjdgus/Data_Analytics_for_Age_friendly_busan#224]
부산의 노인들의 여가 등 사회참여가 부진한데, 이는 노인들이 참여할 수 있는 프로그램 뿐만 주변에 여가활동을 할 수 있는 시설도 부족해서라고 생각합니다. 경로당 이용자들이 생각한 활성화 방안에  운동기구 또는 여가기구의 확충(9.3%) 정도의 낮지 않은 응답율을 보였습니다. 71~80세의 노인분들이 건강을 매우 신경쓰는 만큼  경로당 입지를 제시할때  주변에 체육시설 및 운동 프로그램을 실시 할 수 있을 시설들이 있는 곳을 고려하면 좋을거 같습니다.
참고: [Status and Prospect of the Elderly Living in Small and Medium-sized cities Using the Senior Citizens' Center.pdf](https://github.com/pwjdgus/Data_Analytics_for_Age_friendly_busan/files/8500009/Status.and.Prospect.of.the.Elderly.Living.in.Small.and.Medium-sized.cities.Using.the.Senior.Citizens.Center.pdf)

**Comment by pwjdgus** [comment]
네
