### ISSUE TITLE
경로당 이용률

### ISSUE THREAD

**Issue by hhhhmang** [pwjdgus/Data_Analytics_for_Age_friendly_busan#229]
2020년도부터 코로나로 인해 사회적 거리두기가 시행 됨에 따라 이용률에 영향을 미쳤을 거라 생각됩니다.
구로시 같은 경우에는 현 시점의 상황에 따라 온라인 경로당을 만들었다고 합니다
"온라인경로당’에 참여하고 있는 한 경로당의 어르신은 자신의 일상과 활동 사진을 공유하며 “소년시절로 돌아간 것 같고 재미있어들 합니다. 앞으로 다른 지역들도 현 시점에 맞춰서 온라인으로 접근하는 방향으로 확대되지 않을까 싶습니다.

거리두기가 계속 된다면 앞으로 경로당 이용률은 더 떨어질 것으로 보입니다.

http://cnews.thebigdata.co.kr/view.php?ud=202204110918287484d0a8833aad_23

**Comment by pwjdgus** [comment]
그런 사례가 있었군요
