### ISSUE TITLE
각 경로당 위치를 고려하여 10분이내 거리 밖에 경로당을 짓는게 좋을거 같습니다.

### ISSUE THREAD

**Issue by k69121** [pwjdgus/Data_Analytics_for_Age_friendly_busan#232]
경로당의 상세 위치와 인허가현황 데이터를 찾았습니다. 미래 경로당을 지을떄 이미 지어져있는 경로당과 위치가 겹치거나 너무 가까우면 비효율적일거 같습니다. 데이터를 보면 1990년대를 기준으로 그이후 설치된 경로당이 가장 많다는걸 알수있었습니다. 그렇기에 비교적 최근인 2000년을 기준으로 그 이후 지어진 경로당이 미래에 도 남아있다는걸 전제로 경로당 입지서정기준에 현 경로당 도보 10분거리 밖에 짓는다는 선정 기준을 추가하는건 어떨까요?

**Comment by sj2305** [comment]
기존 경로당과의 거리와 주변 고령자들 거주 위지 등도 같이 고려하면 좋을 것 같습니다.
