### ISSUE TITLE
추가 입지요건 우선순위 부여하기

### ISSUE THREAD

**Issue by MMIINNNN** [pwjdgus/Data_Analytics_for_Age_friendly_busan#248]
이때까지 이슈에 편의시설과의 거리라던가  고도가 높지 않은 곳을 고려한다던가 등, 입지요건을 추가를 제시하는 의견이 많았고
주거수준, 교육수준과 같은 사항도 고려되면 좋겠다고 생각합니다. 하지만 이 모든 것을 동시에 고려하는 것은 불가능하기 때문에
우선순위를 부여하거나 가점제로 입지분석에 고려하는 것을 제안합니다. 

입지분석에 고려할 항목 수에 따라 우선순위 부여를 할지 가점을 부여할지 나눠서 생각했습니다.
우선 추가 입지요건을 중요도에 따라 분류했을 때 고려할 항목 3개 이하라면 우선순위를 부여하고
 4개 이상일 경우 가점을 부여하는 방식을 채택하려고 합니다.

기본적으로 우선순위 부여가 가점보다 가시성이나 명확하다는 점에서 더 낫다고 판단해서 항목이 3개 이하일 때는 사용하지만
항목 수가 4개 이상으로 넘어가고 더 많아졌을 때 우선순위 부여 방식을 채택한다면 후 순위의 항목이 의미가 없는 지표가 되기 때문에 가점제가 더 적합하다고 생각합니다.
또, 우선순위를 나열할 경우 항목의 조건을 구체적으로 설정하여, 더 우선순위의 조건이 동일할 때 해당된다면 우위를 주는 방식을 생각하고 있고
가점제의 경우, 중요도에 따라 항목 별로 비중을 다르게 하여 변별력을 부여하고  항목의 조건에 얼마나 부합하는지에 따라 점수를 차등 부여하려고 합니다.
예를 들어, 근린생활시설과 10분거리에 위치하면 3점 20분거리라면 2점을 부여하는 식입니다.

현재까지 제안된 항목들은
1. 근린 생활 시설과의 인접성 (편의시설)
2. 휴식 시설과의 인접성 (공원, 산책로)
3. 노인 무료 급식소과의 인접성
4. 문화 시설과의 인접성
5. 인지성 (찾기쉬운, 안전)
6. 기존 경로당 위치
7. 버스 정류장과의 인접성
8. 독거노인 많을수록 설치
9. 고도 (위치)
10. 공시지가 (돈)
11.교육수준
12.소득수준
13.주거수준
등이 있는데 1,2,3,4 항목들은 노인들의 편의에 확실히 도움이 되겠지만 도심행정구에 편중돼있어서 모든 행정구에 적용하면 오류를 범할 수 있고
5,6,7,8 항목의 경우는 행정구 별 구분없이 적용가능하고 9,10,11,12,13 항목은 행정구 별 구분이 필요하다고 생각합니다.

제안 된 항목들이 편의성에 초점을 맞춘 것들도 있고 복지 형평성에 초점 맞춘 것이 있어 상충되는 부분이 존재합니다.
따라서 중요도에 따라 분류를 하되, 입지조건의 방향을 정해야 할 것 같습니다. 

이 부분에서 상충되는 항목들을 같이 지표로 활용할 방법이 있다면 피드백 주시면 감사하겠습니다.

**Comment by TayJeong** [comment]
우선순위를 생각못했는데 현재 입지요건 많이 있는 상황인데 좋은 아이디어인 것 같아요!!

**Comment by k69121** [comment]
좋은 의견 감사 합니다. 현재 프로젝트는 최종적으로 미래에 대한 경로당 입지 분석 입니다.  과연 미래에도 공원, 무료 급식소, 다른 시설 등등이 그 자리에 남아있을까요? 저는 어디 까지나 미래 경로당 의 최적의 입지에 대해 알려주는 프로그램이라고 생각합니다. 그 주변의 다른 시설들의 호환성, 주변 경로당 의 위치 등등 그에 관해서는 설치자가 고민해야되는 부분으로 저희가 고려해야할 부분은 아니라고 생각합니다.  하지만 다른 요소들 과 에 있어 우선순위를 설정하자는 의견은 정말 좋은거 같습니다.

**Comment by sj2305** [comment]
기존경로당의 위치를 파악하거나 새로운 경로당을 설치할때 주변 환경을 고려하게 되는데
이 '주변환경' 안에 생활시설 휴식시설 등이 포함된다고 생각됩니다.
일단 제 생각엔 위치와 관련된 요소(6 or 9)의 우선순위를 최대한 높에 잡는것이 좋아보입니다.

**Comment by MMIINNNN** [comment]
피드백 정말 감사합니다! 모든 요인을 고려하겠다는 것은 아닙니다. k69121 님 말씀처럼 최적 입지에 대한 프로그램이 메인이 되어야 하는 것이 맞지만 주변 시설이 입지분석에 직관되는 것도 부분 존재한다고 생각합니다. 하지만 주변시설을 고려하는 것의 한계점 방향성에 대해 조금 더 고민을 해봐야 할 것 같습니다. 감사합니다!

**Comment by MMIINNNN** [comment]
의견감사합니다 :)
