### ISSUE TITLE
여정시간 계산 코드 개선방안

### ISSUE THREAD

**Issue by Choiyuhyeon** [pwjdgus/Data_Analytics_for_Age_friendly_busan#258]
GIS에 관한 코드에 여정시간에 관련된 코드가 아래와 같이 기재되어 있었습니다.
trip_times = [5, 10, 15, 20, 25, 30]  # 분 단위의 여행시간, 5분거리내
travel_speed = 4.5  # 걷는 속도 (km/hour)
위 코드에서 걷는 속도는 일반인들이 걷는 속도 입니다. 걷는 속도를 변경하거나 그것이 어렵다면 추가적으로 travel_old_speed 넣어 노인들의 평균 속도인 1.23(km/hour)을 추가하는 것 어떻게 생각하시나요?
좀 더 노인에게 맞춰진 거리를 계산하는 것에 대해 도움이 될 것 이라 생각합니다.

**Comment by k69121** [comment]
일반인 이 아닌 고령 인구 대상인 모델이니 걷는 속도 자체를 변경 하는 게 좋을 거 같습니다. 노인들의 평균 속도가 1.23 정도인지 몰랐네요. 정말 좋은 거 같습니다.

**Comment by Choiyuhyeon** [comment]
좋은 평가 감사드립니다.

**Comment by pwjdgus** [comment]
4.5 값만 변경하면 됩니다!

**Comment by Auint** [comment]
좋은 제안인 거 같습니다. 

다만 제안한 수치가 어떤 근거로 도출되었는지 따로 찾아본 결과
아래와 비슷한 자료를 가지고 제안을 하신 것 같습니다.
(https://m.segye.com/view/20211110517579)

앞으로 어떠한 이유(혹은 근거)로 제시를 하였다. 라고 추가 한다면 완벽할 것 같습니다.

**Comment by sj2305** [comment]
좋은 생각입니다.

**Comment by Choiyuhyeon** [comment]
넵
