### ISSUE TITLE
Label을 깔끔하게 수정하였습니다.

### ISSUE THREAD

**Issue by k69121** [pwjdgus/Data_Analytics_for_Age_friendly_busan#270]
Label을 두 종류로 구별하여 앞은 ~~관련 ~~ 이런 식으로 해주시면 됩니다. 
예시로 
[입지 관련] 
[Data 관련] [코드]

이런 식으로 해주 시면 됩니다.

의견 Label은 조금 어색한 감이 있어 그냥 삭제 하였습니다. 그냥 ~~관련 으로 Label 달아주시고 ~~관련 코드 이면  코드Label까지 두 개 같이 달아 주시면 될 거 같습니다.

**Comment by Auint** [comment]
수고하셨습니다.
전체적으로 분류체계와 같은 규칙을 따로 정리하여 wiki나 README에 추가하여 지속적으로
관리할 수 있게 하면 좋을 것 같습니다.
