### ISSUE TITLE
성비와 결혼여부를 이용률 요소에 추가하는것이 좋을거 같습니다.

### ISSUE THREAD

**Issue by k69121** [pwjdgus/Data_Analytics_for_Age_friendly_busan#277]
#276 
본 논문을 살펴보면 남자 노인은 모두 유의한 영향이 없었으나 여자 노인은 친구에서 통계적 유의한 영향이있었던것을 알 수 있습니다. 또한 배우자가 있는 노인과 이혼 한 노인의 경로당 이용률을 살펴 보았을 떄  배우자와 동거한 노인이 경로당 이용률이 높았던 것으로 볼떄 여성 노인이 경로당 이용률이 높다는 것을 알 수 있습니다. 이로써 여자가 남자보다 생활 형편에서 안정되고 주거 형태가 편안할수록 이용 만족도를 높게 인식한다는 것을 알 수 있습니다. 그렇기에 이용률 요소에 성비와 결혼 여부를 추가하여 계산하는 것이 좋을거 같습니다.

**Comment by Auint** [comment]
잘하셨습니다.

추가적으로 수정만 하시면 좋을 것 같습니다.

**Comment by k69121** [comment]
감사합니다!
