### ISSUE TITLE
편의시설 데이터 시각화는 어떨까요?

### ISSUE THREAD

**Issue by gymdong** [pwjdgus/Data_Analytics_for_Age_friendly_busan#278]
향후 진행 방향의 4. 입지분석을 위한 편의시설에 대한 데이터 추가.(무료급식소, 종합병원, 약국)
여기서 무료급식소와 종합병원 데이터가 추가되어 있는 것으로 알고 있는데, 이 데이터를 활용하기 위해 지도에 마킹하여 나타내는 것은 어떨까요? 괜찮으면 진행해보려고 합니다.

**Comment by Choiyuhyeon** [comment]
확실히 입지분석을 편리하게 해줄 것 같습니다.

**Comment by sj2305** [comment]
좋은 것 같습니다.

**Comment by hhhhmang** [comment]
동의합니다
