### ISSUE TITLE
편의시설 약국 데이터 추가했습니다.

### ISSUE THREAD

**Issue by gymdong** [pwjdgus/Data_Analytics_for_Age_friendly_busan#284]
#282 풀 리퀘스트 올렸으며 종합병원, 무료급식소, 약국 그 외에도 필요한 편의시설 데이터가 있다면 추가할 예정입니다. 혹시 추가할 편의시설에 대한 의견 있으시면 말씀 부탁드립니다.

**Comment by winnersupa** [comment]
개인적으로는 편의점도 있으면 좋을 것 같습니다.

**Comment by qkrxodnr** [comment]
가벼운 등산로나, 야외 운동시설 (산스장, 공원 등) 에 대한 정보도 있으면 좋을 것 같습니다!
