### ISSUE TITLE
고도 및 경사도 분석 코드

### ISSUE THREAD

**Issue by pear-c** [pwjdgus/Data_Analytics_for_Age_friendly_busan#290]
#288 
구글 api를 이용하여 찾고자 하는 장소의 위도,경도 및 이를 통한 고도 값을 얻을 수 있었습니다.
이 값과 중심지의 위도,경도와 비교하여 두 지점의 직선 간 **최단거리**(straight_way)를,
고도를 비교하여 두 지점 간 **고도차**(h)를 구할 수 있습니다.

최종적으로, 이 두 값을 이용하여 아크탄젠트(역함수)를 사용하면 라디안 값을 얻을 수 있고, 이를 우리가 흔히 아는 PI각도로
변환할 수 있습니다.
- **rad = atan2(h, straight_way)**
- **deg = (rad*180)/math.pi**

이동시간 계산 시 경사도와 고도 값을 적용시킨다면 보다 정확한 값이 도출될 거라 생각합니다.

**Comment by qkrxodnr** [comment]
괜찮은 수식 같습니다.

**Comment by Syunoh** [comment]
좋은 의견이라 생각됩니다.

**Comment by Sagongmin** [comment]
좋은 아이디어입니다.

**Comment by pwjdgus** [comment]
👍👍
