### ISSUE TITLE
코드 개선

### ISSUE THREAD

**Issue by Sagongmin** [pwjdgus/Data_Analytics_for_Age_friendly_busan#294]
![스크린샷 2022-05-26 03 37 50](https://user-images.githubusercontent.com/87919031/170342918-42805dd5-ebee-4974-8b38-77e8f73cc742.jpg)
Busan_Senior_Center(BSC)의_시급한_개선을_위한_입지_분석_모델.ipynb에서 fig.ax = center(G_Jeonggwan) -> 
fig,ax = center(G_Jeonggwan)로 고치면 오류수정이 가능한가요?

**Comment by pwjdgus** [comment]
네 가능합니다  fig.ax => fig, ax
