### ISSUE TITLE
고도를 포함하여 지도 위에 나타내었습니다.

### ISSUE THREAD

**Issue by k69121** [pwjdgus/Data_Analytics_for_Age_friendly_busan#298]
#315

```find_ten_min_and_grade``` 에서 14번쨰줄 계산식을 수정 하면 더 좋은 결과가 나올 거 같습니다.

**Comment by Choiyuhyeon** [comment]
노인 걸음걸이 속도 반영해주셨네요 감사합니다

**Comment by k69121** [comment]
넵 노인 걸음 속도 의견 주셔서 덕분에 반영했어요. 감사합니다.
