### ISSUE TITLE
다른 지역과의 경로당 이용률 비교 분석 도움 받으려 합니다.

### ISSUE THREAD

**Issue by MwaungMwaung** [pwjdgus/Data_Analytics_for_Age_friendly_busan#299]
[다른 지역과의 경로당 이용률 비교](https://github.com/pwjdgus/Data_Analytics_for_Age_friendly_busan/issues/193#issue-1205758266) 분석 함께 하실 사람 있나요.

관심 있으신 분들은 이 문제에 대해 함께 고민하고 조사해주셨으면 좋겠습니다.

현재 저는 농어촌 지역과 도시 지역의 차이를 이용률 격차의 원인으로 두고 조사하고 있습니다.
혹시 다른 방향의 아이디어 있으신 분은 이슈 달아주시면 감사하겠습니다. 안 달고 조사하셔도 됩니다.

**Comment by SIMOOLOOK** [comment]
혹시 위의 내용을 추가적으로 분석하시려는 이유를 알 수 있을까요?

**Comment by MwaungMwaung** [comment]
> 혹시 해당 내용에 대해 추가적으로 조사하시려는 목적이 뭔지 알 수 있을까요??
> 
> 저도 #193 의 내용이 흥미로워 조사를 했었는데, 도시지역과 비도시지역의 노인복지시설 인프라 차이가 이용률에 가장 큰 영향을 미친다는 결론이 나왔습니다. ( 해당 이슈의 댓글에 참고자료와 함께 제시하였습니다.)
> 
> 만약 도시와 비도시 간의 인프라 차이가 이용률 격차의 주된 이유라면 현재 저희 프로젝트에 유의미한 결과를 주지 못할 것이라 생각했는데, 혹시 프로젝트에 반영할만한 다른 이유를 찾으신건가요? 더 조사하시려는 이유가 알고 싶습니다.

제가 추가 조사가 필요하다고 생각하는 이유는 이렇습니다.

 첫 번째로, 지역을 분류하는 기준을 늘려서 다른 기준으로 조사해볼 수 있습니다. 도시 지역과 비도시 지역으로 나누었을 때 이용률 차이를 결정짓는 주요 요인이 인프라 차이인 것은 사실입니다. 하지만 다른 분류 기준으로 도시를 구분하고 비교해보면 어떨까요? 예를 들어서, 분류 기준을 교육 시설이 밀집된 교육 도시와 일반 도시로 본다면 교육 도시의 경로당 이용률은 일반 도시와 유의미한 차이를 보일까요?
[도시의 이해 1장](https://web.joongbu.ac.kr/cmm/fms/FileDown.do;jsessionid=4482B049FDFF4506A7BF07E6BD728C63?atchFileId=FILE_000000000051429&fileSn=1)

 두 번째로, 도시 지역 간에도 이용률 차이에 영향을 미치는 요인이 존재합니다. 서울은 부산에 비해서 더 대도시지만 부산에 비해 경로당 이용률이 높습니다. 광주광역시는 조사 연도인 2020년 기준으로 1km^2당 약 2,902.5명, 대구광역시는 1km^2당 약 2,750명입니다. 즉, 광주광역시가 더 인구 밀도가 높으며 대도시 비중이 크지만 경로당 이용률과 향후 이용 희망률에서 크게 앞섭니다.  
[광주와 대구 인구](https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1B040A3)
[광주와 대구 면적](https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1ZGA17&conn_p-ath=I2)

 세 번째로, 지역의 범위를 넓혀서 국가 단위로 경로당 이용률 차이를 분석해볼 수 있습니다. 또는 반대로 범위를 좁혀서 부산 행정 구 사이에 경로당 이용률 차이의 원인을 분석하는 방향도 있습니다. 

이처럼 다른 지역 간의 경로당 이용률 차이 원인의 다양한 분석 방향을 떠올리고 있는데, 저 혼자 조사해보기엔 양이 많았습니다.
또한 다른 분들이 이 주제로 저보다 좋은 아이디어와 분석을 제시하실 수 있을 것이라고 생각하여 조사 도움을 요청하였습니다.

추가로 타지역 조사의 필요성에 대한 논지와는 조금 벗어나는 의견이지만, 지역 간 비교를 통해 얻어낸 유의미한 변수를 이용률 영향도에 따라 가중치를 두어 입지 선정 식에 결합한다면 본 조사가 프로젝트에 유의미한 도움이 될 것 같습니다.

**Comment by SIMOOLOOK** [comment]
제가 도시 지역 간에 이용률 차이에 대해서는 생각해보지 못했네요.

부산과 유사한 정도의 인프라를 갖춘 대도시 지역 중 부산의 경로당 이용률이 낮은 이유를 분석해보면 유의미한 결과가 나올 수도 있을 것 같습니다. 해당 내용에 대해 조사 해보겠습니다.
