### ISSUE TITLE
경로당 도우미에 대한 의견

### ISSUE THREAD

**Issue by dongchan0330** [pwjdgus/Data_Analytics_for_Age_friendly_busan#300]
경로당의 복지 중에 도우미를 하시는 분이 있는데 도우미에 대한 설명을 추가하고자 합니다.
의견이 있으신 분은 자유롭게 말씀해주시면 감사하겠습니다.

**Comment by SIMOOLOOK** [comment]
도우미에 대한 설명이 현재 프로젝트에 왜 필요한지 이해가 잘 되지 않습니다. 혹시 추가로 설명 부탁 드려도 될까요?

**Comment by dongchan0330** [comment]
경로당의 도우미는 복지시설의 복지 중에 하나입니다. 어르신분들이 경로당을 가는 이유 중에 대부분은 외로움을 달래기 위해서 입니다. 물론 주위 어르신분과 함께 있지만 어르신뿐만 있다면 생활에 한계가 있기 때문에 도우미가 필요합니다. 경로당의 환경을 정리하고 어르신들의 식사를 준비하며 어르신분들과 대화하며 건강하고 유익한 노후를 즐길 수 있습니다. 그래서 저는 경로당 도우미의 수 및 도우미에 대한 만족도에 대해 조사하고자 합니다.   
 
-----Original Message-----

**Comment by SIMOOLOOK** [comment]
답변 주신 내용은 우리 프로젝트의 내용인 경로당 '입지선정'과는 거리가 있어 보입니다. 정책 제안 관련해서는 좋은 아이디어 같네요ㅎ

**Comment by hhhhmang** [comment]
@SIMOOLOOK 동의합니다

**Comment by winnersupa** [comment]
@SIMOOLOOK 저도 동의합니다
