### ISSUE TITLE
CONTRIBUTING.md 파일 추가

### ISSUE THREAD

**Issue by SIMOOLOOK** [pwjdgus/Data_Analytics_for_Age_friendly_busan#304]
현재까지 올라온 issue 작성과 관련된 의견을 조합하여 issue 작성 가이드라인 파일을 추가하려 합니다.
내용 요약과 참고한 issue 공유하겠습니다.

1. 새로운 이슈 제출 전 해당되는 라벨을 검색하여 앞서 관련된 내용의 이슈가 있는지 확인합시다. (#218) 
2. 라벨링을 활용합시다. (#270)
3. 의견 제시 시, 근거 자료도 함께 제시합니다.(#213)
4. 통계 자료나 참고자료는 가능한 최근 자료를 사용합니다.(#189)
5. 제시한 issue에 적절한 답변이 완료되면 issue를 닫아줍시다.(#175)
6. 공론화 되어 활발하게 논의되고 있는 이슈는 milestone 활용합시다.(#122)
7. 적절한 사람을 언급합니다.

**Comment by Choiyuhyeon** [comment]
의견을 조합하기에 좋은 방안같습니다
