### ISSUE TITLE
README.md 수정

### ISSUE THREAD

**Issue by SIMOOLOOK** [pwjdgus/Data_Analytics_for_Age_friendly_busan#306]
국내 참고자료 부분에서 카카오 맵 검색 방법을 수정하려 합니다. 

기존 : (지역이름) (노인복지) or (지역이름) (경로당)
변경 : (지역이름) (경로당)

카카오 맵에서 (지역이름)(노인복지)라고 검색 시 경로당 이외의 다른 노인복지시설도 함께 나타나는 것을 확인하였습니다.
명확하지 않은 검색방법이라 판단하여 수정하였습니다.

참고)
노인복지시설은 7가지 종류로 분류되고, 경로당은 그 중 하나인 노인여가복지시설에 해당됨.

노인복지법 제 4장 제 31조, 제 36조(https://www.law.go.kr/%EB%B2%95%EB%A0%B9/%EB%85%B8%EC%9D%B8%EB%B3%B5%EC%A7%80%EB%B2%95)

**Comment by winnersupa** [comment]
수정하신 내용에 동의합니다
