### ISSUE TITLE
BSC 입지 분석 모델의 수식에 대한 issue(1)

### ISSUE THREAD

**Issue by jinyoungkimm** [pwjdgus/Data_Analytics_for_Age_friendly_busan#74]
![스크린샷(22)_LI](https://user-images.githubusercontent.com/100742333/162552516-38ef1ce3-57a0-48b8-a298-37ce0b5d417a.jpg)
SC_proper은 행정'동' 단위인데, 이걸 구하는 수식에 보면 "OP_admin area * SC_per one"이라고 돼 있습니다.  

제가 제기하고 싶은 issue는 OP_admin area의 단위는 행정 "동"인데, SC_per one이 행정 "구" 단위이면 구하려고 하는
행정 "동" 단위 적절한 경로당 수(SC_proper)의 값의 의미가 왜곡될 것 같습니다! 만약 구하고 싶은 것이 행정 "동" 단위의
적정한 경로당 수라면, 아래와 같이 수식을 변경해야 할 것 같습니다.
SC_proper(.....) = OP_admin area * (행정"동" 1명당 필요한 경로당 수)

**Comment by pwjdgus** [comment]
의견 감사합니다 파일 full req하시면 반영하겠습니다
