### ISSUE TITLE
BSC 입지 분석 모델의 수식에 대한 issue(2)

### ISSUE THREAD

**Issue by jinyoungkimm** [pwjdgus/Data_Analytics_for_Age_friendly_busan#75]
![스크린샷(26)_LI](https://user-images.githubusercontent.com/100742333/162554475-81cb1722-0bde-43c5-8faa-a8ae2324c17e.jpg)

위 그림에서 빨간색으로 칠한 수식은 직관적으로 이해하기가 어렵습니다. 아래의 식은 위의 식과 같은 값을 산출하며 더 직관적이다.
Renual  equation_1 : SC_per one(SC_use rate , SC_member) = (1/SC_member) x SC_use rate (검증 완료함)

**Comment by pwjdgus** [comment]
추후 요구 할 것이지만 현재 ppt상의 변수 이름의 경우 매우 눈에 잘 들어오지 않는 형태입니다.
이러한 변수를 보다 간결하게 나타내는 방법이 있을까요
