### ISSUE TITLE
BSC 입지 분석 모델에 대한 PPT 오류 수정 및 개선

### ISSUE THREAD

**Issue by jinyoungkimm** [pwjdgus/Data_Analytics_for_Age_friendly_busan#76]
![스크린샷(32)](https://user-images.githubusercontent.com/100742333/162555060-5d4a9cdc-ba18-40be-9861-99a12126740b.png)
위 식에서 SC_admin area를 사용해놓고는 그 아래에서는 SC_admin_area를 SC_neighbor로 표기를 하고 있습니다. 그리고 위 스크린샷의 우측 하단의 pseudo code를 약간 detail하게 아래와 같이 수정을 하였습니다.
![스크린샷(34)](https://user-images.githubusercontent.com/100742333/162555150-fc82e1c8-0167-454c-b855-b064111bee0f.png)

**Comment by pwjdgus** [comment]
수정하신 파일 full req하시면 반영하겠습니다
