### ISSUE TITLE
코드 개선 의견

### ISSUE THREAD

**Issue by k69121** [pwjdgus/Data_Analytics_for_Age_friendly_busan#77]
+ 판다스 함수를 통해 코드 간결화가 가능할거같습니다.
    (예시) 본문에서는 for문을 일일이 사용하였는데 판다스 함수인 loc(),iloc(),iterrows(),itertuples(),iteritems()및apply()메소드를 사용하여 코드간결화가 가능함.

+ 노인 1명당 경로당수를 구해서 0. 대의 소수점이 나오는데 이걸 이걸 1명당이 아닌 100명, 1000명단위로 바꾸면 좋을거같습니다.

+ groupby() 함수를 이용해 데이터프레임을 범주별로 묶을 필요가있습니다.

+ 이동시간에 버스, 전철등의 교통 데이터를 추가하여 접근성및 이용률을 다시 계산할 필요가 있을거같습니다.

+ 유동인구와 노인 평균 수명도 고려하여 이용률을 재검토할 필요가 있습니다.

**Comment by pwjdgus** [comment]
1. 판다스를 통해 코드 간결화 가능할 것 같습니다.
 (예시) 본문에서는 for문을 일일이 사용하였는데 Pandas 메서드  ```loc(),iloc(),iterrows(),itertuples(),iteritems(),apply()``` 를 사용하여 코드 간결화 가능함. 
=> 이 부분은 강의 시간에 이야기 했던 부분입니다.  구체적으로 어느 곳에 메서드를 적용 시킬 계획인가요?

2. 노인 1명당 경로당 수를 구해서 0. 대의 소수점이 나오는데 이걸 이걸 1명당이 아닌 100명, 1000명단위로 바꾸면 좋을 것 같습니다. 
=> 통계적으로는 1천명 단위로 나타내는 것이 좋습니다. 단, 1명당으로 계산을 했던 이유는 한번 생각해보시면 좋을 것 같습니다.

4. groupby() 함수를 이용해  DataFrame을 범주별로 묶을 필요 있습니다.
=> 마찬가지로 구체적인 제시를 해주세요

5. 이동 시간에 버스, 전철등의 교통 데이터를 추가하여 접근성 및 이용률을 다시 계산할 필요가 있을 것 같습니다.
=> 확인했습니다. 개선하여 pull req 하시면 됩니다.

7. 유동 인구와 노인 평균 수명도 고려하여 이용률을 재검토할 필요가 있습니다.
=> 그 부분은 이용률 보다는 미래 인구 예측 수식에 사용되는 것이 더 바람직해 보입니다.
