### ISSUE TITLE
경로당 이용률 관련 의견

### ISSUE THREAD

**Issue by gymdong** [pwjdgus/Data_Analytics_for_Age_friendly_busan#80]
발표자료와 데이터에 사용된 경로당 이용률 데이터의 시점을 명시하면 좋을 것 같습니다.
코로나 이전과 이후의 경로당 이용률이 조금 차이가 있을 것인데 추후 필요할 경로당의 숫자를 정확히 계산하기 위해서는 코로나 이전과 이후의 이용률을 비교하기 위해 현재 사용된 데이터의 시점이 필요할 것 같습니다.

**Comment by pwjdgus** [comment]
이용률 데이터는 2019년도 밖에 없습니다.
데이터의 부족으류 인한 한계라고 뷸 수 있습니다.

따라서 이용률을 사회적 참여요소로 접근 할 방법을 요청한 것 입니다

**Comment by gymdong** [comment]
2020년의 데이터를 풀리퀘스트 올려놓은 상태인데 데이터를 정리하고 기존의 데이터는 19년도 데이터임을 명시하고 비교해서 올려도 될까요?
