### ISSUE TITLE
wiki 작성을 제안합니다.

### ISSUE THREAD

**Issue by BlueArcticFox** [pwjdgus/Data_Analytics_for_Age_friendly_busan#82]
### 이러한 내용과 더불어 참고 사이트까지 정리하여 wiki에 통합하는것이 더 효율적일 것이라 생각됩니다.
- ex1) 해당 프로젝트의 개요나 목표
- ex2) 로케이션 인텔리젼스(LI: Location Intelligence)와 같은 관련용어
- ex3) pandas, numpy, osmnx와 같은 주로 사용되는 라이브러리에 관한 내용과 참고사이트

**Comment by hhhhmang** [comment]
동의합니다

**Comment by TayJeong** [comment]
좋은 생각인것 같습니다

**Comment by pwjdgus** [comment]
좋은 의견입니다 wiki작성 하시면 될 듯 합니다

**Comment by tam31** [comment]
좋은 생각입니다
