### ISSUE TITLE
미래 노인인구 예측 수식을 쓰지말고 데이터를 직접적으로 가져오는건 어떨까요?

### ISSUE THREAD

**Issue by k69121** [pwjdgus/Data_Analytics_for_Age_friendly_busan#85]
[인구로 보는 대한민국](https://kosis.kr/visual/populationKorea/PopulationByNumber/PopulationByNumberMain.do?mb=N)

국가에서 70대까지 계산한 미래 노인인구 예측이 있습니다. 이걸 그대로 가져오는건 어떨까요?

**Comment by qkrxodnr** [comment]
보기쉽고 좋은것 같습니다.
