### ISSUE TITLE
보기 불편한 표 수정 의견

### ISSUE THREAD

**Issue by WaiCat** [pwjdgus/Data_Analytics_for_Age_friendly_busan#86]
Busan_Senior_Center(BSC)의_시급한_개선을_위한_입지_분석_모델_예측_평가.ipynb 자료에서 OUT[15], OUT[17], OUT[19]의 경로당수, 적절한 경로당 수, 필요한 경로당 수를 구하는 표에서  out15에서는 중구였다가 out17은강서구로나오고 out19에서는 필요한 경로당 수만 나와 보기가 어렵고 불편해서 세가지 다 중구로 통일하고 세가지 목록을 다 나타낼 필요가 있습니다.

**Comment by Sagongmin** [comment]
WaiCat님 의견에 동의합니다.

**Comment by pwjdgus** [comment]
좋은 의견입니다.  하지만 Out[31]번을 보시면 종합적으로 나옵니다.

출력물이 불편하다면 pandas를 통해서 테이블을 수정하면 됩니다.
