### ISSUE TITLE
경로당 설치시 고려해야할점

### ISSUE THREAD

**Issue by hhhhmang** [pwjdgus/Data_Analytics_for_Age_friendly_busan#91]
적절한 경로당 수를 계산하여 미래 필요한 경로당 수 상위 4개 행정 동을 경로당이 시급하게 필요한 후보지로 선정한다고 되어있는데 증설해야하는 경로당 수를 계산할 때 구청이 가지고 있는 노인복지사업 비용을 추가적으로 고려해야한다고 생각합니다

**Comment by pwjdgus** [comment]
미래에 대한 경로당 수 및 입지 제시이기 때문에 이부분은 반영될 필요가 없다고 생각합니다
