### ISSUE TITLE
초고령도시로 인한 연령 제한 의견

### ISSUE THREAD

**Issue by TAEYOUNGY00N** [pwjdgus/Data_Analytics_for_Age_friendly_busan#94]
‘2015 인구센서스’에 따르면 동구 · 서구 · 중구 등 부산의 구도심 3개 구가 초고령 도시가 됐습니다. 동구 어느 경로당의 경우 70세부터 회원이 될 수있습니다. 이에 따라 구마다 특징을 적용하여 노령 인구 집계를 하면 더 효율적일 것이라고 생각합니다.

[관련자료] : (https://www.joongang.co.kr/article/20573526#home)

**Comment by hhhhmang** [comment]
경로당을 증설하여 과밀화를 방지하면 연령 제한을 해결할 수 있을까요 ?
