### ISSUE TITLE
입지분석을 위한 기준 추가

### ISSUE THREAD

**Issue by qkrxodnr** [pwjdgus/Data_Analytics_for_Age_friendly_busan#95]
고령인구 중에서도 젊은층과 고령층을 나누어서 밀집도를 계산해야 할것 같습니다. 고령인구 중에서도 젊은층과 고령층이 골고루 섞여서 분포 되어 있으면 이대로 유지하고, 젊은층과 고령층의 밀집도가 눈에 띄게 차이가 난다면 이를 분석하여 입지분석의 기준에 포함 시키면 좋을것 같습니다.
고령인구 중에서도 젊은 층 보다는 연세가 더 많으신 분들쪽에 좀 더 가까이 설치하는것도 입지분석을 할때 고려한다면 입지분석의 효율을 높일 수 있을 것 같습니다.

**Comment by hhhhmang** [comment]
광역시별 연령대 인구수는 0세~100세 10 단위로 나와있지만
광역시 구별 연령대 인구수는 60세 이후부터는 나와있지 않은 거 같습니다
https://sdfrudn.tistory.com/entry/%EC%9A%B0%EB%A6%AC%EB%82%98%EB%9D%BC-%EC%9D%B8%EA%B5%AC-%EC%88%9C%EC%9C%84-%EC%A7%80%EC%97%AD%EB%B3%84-%EB%82%98%EC%9D%B4%EB%B3%84-%EB%8F%84%EC%8B%9C%EB%B3%84-%EC%B2%B4%ED%81%AC

**Comment by qkrxodnr** [comment]
국내통계포털에 나와있는것 같습니다!
https://kosis.kr/statHtml/statHtml.do?orgId=101&tblId=DT_1IN2010&vw_cd=MT_ZTITLE&list_id=A11_2015_1_10_001&scrId=&seqNo=&lang_mode=ko&obj_var_id=&itm_id=&conn_path=MT_ZTITLE&path=%252FstatisticsList%252FstatisticsListIndex.do

**Comment by qkrxodnr** [comment]
좋은 자료 감사합니다!

**Comment by pwjdgus** [comment]
좋은 의견입니다 구체적으로 입지 기준에 어떻게 적용을 할 수 있을까요?

**Comment by DongUk-Park** [comment]
2020년 기준 기대 수명은 83.5 세이고(https://www.index.go.kr/unify/idx-info.do?idxCd=8016), 고령 사회 기준이 65세 인 것을 감안하여 그 가운데 지점인 74.25세, 즉 74세를 고령 인구의 젊은층과 고령층을 나누는 기준으로 삼으면 어떨까요?

**Comment by qkrxodnr** [comment]
입지 기준에 적용할 방법으로는 밀집지역의 구체적인 평균 나이대를 구해서 시각화 한 후에 수식에 추가한다든지 해서 입지분석을 하면 좋을것 같습니다.

**Comment by pwjdgus** [comment]
그런데 고령자라는 기준이 정해져있어 보입니다.

임의로 변경하는 방법은 기존의 기준을 엎을 수 있는 구체적인 근거가 있어보이는데 그 방법은 매우 어려워 보입니다..
