### ISSUE TITLE
경로당 설치지 고려할점

### ISSUE THREAD

**Issue by jihoonjeong56** [pwjdgus/Data_Analytics_for_Age_friendly_busan#98]
경로당 설치시 요구 조건에 이동거리 뿐만 아니라  교통에 관해서도 고려했으면 좋겠습니다. 차량이 많아진 만큼 교통사고의 위험률도 대폭 상승하고 있으며, 거동이 불편한 노인분들 같은경우 작은 경상에 불과한 충격이라도 크게 다칠수 있습니다. 경찰청에서 정보공개에 공공데이터를 보면 지역별, 상황별 다양하게 제공되어있기때문에 고려하면 좋을거 같습니다.
https://www.police.go.kr/www/open/publice/publice2020_0401.jsp(경찰청 교통사고현황)

**Comment by pwjdgus** [comment]
#92 랑 비슷한 의견인 듯 합니다. 작성자와 같이 논의 해보면 어떨까요?
