### ISSUE TITLE
경사도에 따른 이동거리 차이 및 시간 계산 방법

### ISSUE THREAD

**Issue by DongUk-Park** [pwjdgus/Data_Analytics_for_Age_friendly_busan#99]
저는 평지와 경사도에서 발생하는 칼로리 소모의 차이에 대하여 생각해보았습니다.

평지와 경사도에서 발생하는 칼로리 소모의 차이에 대한 퍼센트를 계산하여 이동거리에 비례하도록 대입해주는것입니다.
아래의 링크를 참고하였습니다.
http://contents.kocw.or.kr/contents4/document/lec/2013/Silla/LeeBomjin/1/3.pdf
https://blog.naver.com/PostView.nhn?blogId=2949200&logNo=222190420909

우리는 평지와 경사도에서의 차이만 알면 되기때문에
VO2(산소 섭취량) = 3.5 + 0.1(속도) + 1.8(속도)(경사도) 를 사용하여 

경사로를 걸을 때 VO2 = 3.5 + (0.1xS) + (1.8 x S x G) 
평지를 걸을 때 : VO2 = 3.5 + (0.1xS)
(S: 분당미터 , m/min로 표시
G: 경사도 (5%는 0.05로 입력)

경사로 / 평지 *100 을 통해 몇 퍼센트 더 많은 칼로리를 소모하는지 계산할 수 있습니다. 
-> (3.5 + (0.1xS) + (1.8 x S x G)) / (3.5 + (0.1x*S)) * 100

이 퍼센트를 고도가 다른 두 지점의 직선거리에 곱해주면 고도를 이동거리에 대입할 수 있다고 생각했습니다.

시간은 (거리) = (속도) x (시간) 을 이용해 구해줄 수 있습니다.

**Comment by pwjdgus** [comment]
훌륭한 아이디어 입니다 꼭 반영해서 pull req 하면 좋을 것 같습니다

**Comment by Choiyuhyeon** [comment]
칼로리 소모에 따른 거리계산이 정말 좋은 아이디어 같습니다

**Comment by leeseungmin-kr** [comment]
좋은 아이디어 인거 같습니다.
